export const GdtEntryType = {
  FORM: 'FORM',
  CVS: 'CVS',
  ELOPAGE: 'ELOPAGE',
  ELOPAGE_PUBLISHER: 'ELOPAGE_PUBLISHER',
  DIGISTORE: 'DIGISTORE',
  CVS2: 'CVS2',
  GLOBAL_MODIFICATOR: 'GLOBAL_MODIFICATOR',
}
