/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef BASIC_TYPES_H
#define BASIC_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Message proto.gradido.AccountBalance.
 */
struct proto_gradido_account_balance_repeated_t {
    int length;
    struct proto_gradido_account_balance_t *items_p;
};

struct proto_gradido_account_balance_t {
    struct pbtools_message_base_t base;
    struct pbtools_bytes_t pubkey;
    int64_t balance;
    struct pbtools_bytes_t community_uuid;
};

/**
 * Message proto.gradido.DurationSeconds.
 */
struct proto_gradido_duration_seconds_repeated_t {
    int length;
    struct proto_gradido_duration_seconds_t *items_p;
};

struct proto_gradido_duration_seconds_t {
    struct pbtools_message_base_t base;
    uint64_t seconds;
};

/**
 * Enum proto.gradido.EncryptedMemo.MemoKeyType.
 */
enum proto_gradido_encrypted_memo_memo_key_type_e {
    proto_gradido_encrypted_memo_shared_secret_e = 0,
    proto_gradido_encrypted_memo_community_secret_e = 1,
    proto_gradido_encrypted_memo_plain_e = 2
};

/**
 * Message proto.gradido.EncryptedMemo.
 */
struct proto_gradido_encrypted_memo_repeated_t {
    int length;
    struct proto_gradido_encrypted_memo_t *items_p;
};

struct proto_gradido_encrypted_memo_t {
    struct pbtools_message_base_t base;
    enum proto_gradido_encrypted_memo_memo_key_type_e type;
    struct pbtools_bytes_t memo;
};

/**
 * Message proto.gradido.SignaturePair.
 */
struct proto_gradido_signature_pair_repeated_t {
    int length;
    struct proto_gradido_signature_pair_t *items_p;
};

struct proto_gradido_signature_pair_t {
    struct pbtools_message_base_t base;
    struct pbtools_bytes_t pubkey;
    struct pbtools_bytes_t signature;
};

/**
 * Message proto.gradido.SignatureMap.
 */
struct proto_gradido_signature_map_repeated_t {
    int length;
    struct proto_gradido_signature_map_t *items_p;
};

struct proto_gradido_signature_map_t {
    struct pbtools_message_base_t base;
    struct proto_gradido_signature_pair_repeated_t sig_pair;
};

/**
 * Message proto.gradido.Timestamp.
 */
struct proto_gradido_timestamp_repeated_t {
    int length;
    struct proto_gradido_timestamp_t *items_p;
};

struct proto_gradido_timestamp_t {
    struct pbtools_message_base_t base;
    int64_t seconds;
    int32_t nanos;
};

/**
 * Message proto.gradido.TimestampSeconds.
 */
struct proto_gradido_timestamp_seconds_repeated_t {
    int length;
    struct proto_gradido_timestamp_seconds_t *items_p;
};

struct proto_gradido_timestamp_seconds_t {
    struct pbtools_message_base_t base;
    int64_t seconds;
};

/**
 * Message proto.gradido.TransferAmount.
 */
struct proto_gradido_transfer_amount_repeated_t {
    int length;
    struct proto_gradido_transfer_amount_t *items_p;
};

struct proto_gradido_transfer_amount_t {
    struct pbtools_message_base_t base;
    struct pbtools_bytes_t pubkey;
    int64_t amount;
    struct pbtools_bytes_t community_uuid;
};

/**
 * Encoding and decoding of proto.gradido.AccountBalance.
 */
struct proto_gradido_account_balance_t *
proto_gradido_account_balance_new(
    void *workspace_p,
    size_t size);

int proto_gradido_account_balance_encode(
    struct proto_gradido_account_balance_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_account_balance_decode(
    struct proto_gradido_account_balance_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.DurationSeconds.
 */
struct proto_gradido_duration_seconds_t *
proto_gradido_duration_seconds_new(
    void *workspace_p,
    size_t size);

int proto_gradido_duration_seconds_encode(
    struct proto_gradido_duration_seconds_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_duration_seconds_decode(
    struct proto_gradido_duration_seconds_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.EncryptedMemo.
 */
struct proto_gradido_encrypted_memo_t *
proto_gradido_encrypted_memo_new(
    void *workspace_p,
    size_t size);

int proto_gradido_encrypted_memo_encode(
    struct proto_gradido_encrypted_memo_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_encrypted_memo_decode(
    struct proto_gradido_encrypted_memo_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.SignaturePair.
 */
struct proto_gradido_signature_pair_t *
proto_gradido_signature_pair_new(
    void *workspace_p,
    size_t size);

int proto_gradido_signature_pair_encode(
    struct proto_gradido_signature_pair_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_signature_pair_decode(
    struct proto_gradido_signature_pair_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int proto_gradido_signature_map_sig_pair_alloc(
    struct proto_gradido_signature_map_t *self_p,
    int length);

/**
 * Encoding and decoding of proto.gradido.SignatureMap.
 */
struct proto_gradido_signature_map_t *
proto_gradido_signature_map_new(
    void *workspace_p,
    size_t size);

int proto_gradido_signature_map_encode(
    struct proto_gradido_signature_map_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_signature_map_decode(
    struct proto_gradido_signature_map_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.Timestamp.
 */
struct proto_gradido_timestamp_t *
proto_gradido_timestamp_new(
    void *workspace_p,
    size_t size);

int proto_gradido_timestamp_encode(
    struct proto_gradido_timestamp_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_timestamp_decode(
    struct proto_gradido_timestamp_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.TimestampSeconds.
 */
struct proto_gradido_timestamp_seconds_t *
proto_gradido_timestamp_seconds_new(
    void *workspace_p,
    size_t size);

int proto_gradido_timestamp_seconds_encode(
    struct proto_gradido_timestamp_seconds_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_timestamp_seconds_decode(
    struct proto_gradido_timestamp_seconds_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.TransferAmount.
 */
struct proto_gradido_transfer_amount_t *
proto_gradido_transfer_amount_new(
    void *workspace_p,
    size_t size);

int proto_gradido_transfer_amount_encode(
    struct proto_gradido_transfer_amount_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_transfer_amount_decode(
    struct proto_gradido_transfer_amount_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void proto_gradido_account_balance_init(
    struct proto_gradido_account_balance_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_account_balance_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_account_balance_t *self_p);

void proto_gradido_account_balance_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_account_balance_t *self_p);

void proto_gradido_account_balance_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_account_balance_repeated_t *repeated_p);

void proto_gradido_account_balance_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_account_balance_repeated_t *repeated_p);

void proto_gradido_duration_seconds_init(
    struct proto_gradido_duration_seconds_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_duration_seconds_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_duration_seconds_t *self_p);

void proto_gradido_duration_seconds_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_duration_seconds_t *self_p);

void proto_gradido_duration_seconds_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_duration_seconds_repeated_t *repeated_p);

void proto_gradido_duration_seconds_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_duration_seconds_repeated_t *repeated_p);

void proto_gradido_encrypted_memo_init(
    struct proto_gradido_encrypted_memo_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_encrypted_memo_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_encrypted_memo_t *self_p);

void proto_gradido_encrypted_memo_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_encrypted_memo_t *self_p);

void proto_gradido_encrypted_memo_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_encrypted_memo_repeated_t *repeated_p);

void proto_gradido_encrypted_memo_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_encrypted_memo_repeated_t *repeated_p);

void proto_gradido_signature_pair_init(
    struct proto_gradido_signature_pair_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_signature_pair_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_signature_pair_t *self_p);

void proto_gradido_signature_pair_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_signature_pair_t *self_p);

void proto_gradido_signature_pair_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_signature_pair_repeated_t *repeated_p);

void proto_gradido_signature_pair_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_signature_pair_repeated_t *repeated_p);

void proto_gradido_signature_map_init(
    struct proto_gradido_signature_map_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_signature_map_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_signature_map_t *self_p);

void proto_gradido_signature_map_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_signature_map_t *self_p);

void proto_gradido_signature_map_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_signature_map_repeated_t *repeated_p);

void proto_gradido_signature_map_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_signature_map_repeated_t *repeated_p);

void proto_gradido_timestamp_init(
    struct proto_gradido_timestamp_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_timestamp_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_timestamp_t *self_p);

void proto_gradido_timestamp_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_timestamp_t *self_p);

void proto_gradido_timestamp_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_timestamp_repeated_t *repeated_p);

void proto_gradido_timestamp_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_timestamp_repeated_t *repeated_p);

void proto_gradido_timestamp_seconds_init(
    struct proto_gradido_timestamp_seconds_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_timestamp_seconds_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_timestamp_seconds_t *self_p);

void proto_gradido_timestamp_seconds_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_timestamp_seconds_t *self_p);

void proto_gradido_timestamp_seconds_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_timestamp_seconds_repeated_t *repeated_p);

void proto_gradido_timestamp_seconds_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_timestamp_seconds_repeated_t *repeated_p);

void proto_gradido_transfer_amount_init(
    struct proto_gradido_transfer_amount_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_transfer_amount_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_transfer_amount_t *self_p);

void proto_gradido_transfer_amount_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_transfer_amount_t *self_p);

void proto_gradido_transfer_amount_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_transfer_amount_repeated_t *repeated_p);

void proto_gradido_transfer_amount_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_transfer_amount_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
