/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef GRADIDO_TRANSACTION_H
#define GRADIDO_TRANSACTION_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"
#include "basic_types.h"
#include "ledger_metadata.h"

/**
 * Message proto.gradido.GradidoTransaction.
 */
struct proto_gradido_gradido_transaction_repeated_t {
    int length;
    struct proto_gradido_gradido_transaction_t *items_p;
};

struct proto_gradido_gradido_transaction_t {
    struct pbtools_message_base_t base;
    struct proto_gradido_signature_map_t *sig_map_p;
    struct pbtools_bytes_t body_bytes;
    struct proto_gradido_ledger_anchor_t *pairing_ledger_anchor_p;
};

int proto_gradido_gradido_transaction_sig_map_alloc(
    struct proto_gradido_gradido_transaction_t *self_p);

int proto_gradido_gradido_transaction_pairing_ledger_anchor_alloc(
    struct proto_gradido_gradido_transaction_t *self_p);

/**
 * Encoding and decoding of proto.gradido.GradidoTransaction.
 */
struct proto_gradido_gradido_transaction_t *
proto_gradido_gradido_transaction_new(
    void *workspace_p,
    size_t size);

int proto_gradido_gradido_transaction_encode(
    struct proto_gradido_gradido_transaction_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_transaction_decode(
    struct proto_gradido_gradido_transaction_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void proto_gradido_gradido_transaction_init(
    struct proto_gradido_gradido_transaction_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_gradido_transaction_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_transaction_t *self_p);

void proto_gradido_gradido_transaction_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_transaction_t *self_p);

void proto_gradido_gradido_transaction_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_transaction_repeated_t *repeated_p);

void proto_gradido_gradido_transaction_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_transaction_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
