/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef GRADIDO_TRANSFER_H
#define GRADIDO_TRANSFER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"
#include "basic_types.h"

/**
 * Message proto.gradido.GradidoTransfer.
 */
struct proto_gradido_gradido_transfer_repeated_t {
    int length;
    struct proto_gradido_gradido_transfer_t *items_p;
};

struct proto_gradido_gradido_transfer_t {
    struct pbtools_message_base_t base;
    struct proto_gradido_transfer_amount_t *sender_p;
    struct pbtools_bytes_t recipient;
};

/**
 * Message proto.gradido.GradidoDeferredTransfer.
 */
struct proto_gradido_gradido_deferred_transfer_repeated_t {
    int length;
    struct proto_gradido_gradido_deferred_transfer_t *items_p;
};

struct proto_gradido_gradido_deferred_transfer_t {
    struct pbtools_message_base_t base;
    struct proto_gradido_gradido_transfer_t *transfer_p;
    struct proto_gradido_duration_seconds_t *timeout_duration_p;
};

/**
 * Message proto.gradido.GradidoRedeemDeferredTransfer.
 */
struct proto_gradido_gradido_redeem_deferred_transfer_repeated_t {
    int length;
    struct proto_gradido_gradido_redeem_deferred_transfer_t *items_p;
};

struct proto_gradido_gradido_redeem_deferred_transfer_t {
    struct pbtools_message_base_t base;
    uint64_t deferred_transfer_transaction_nr;
    struct proto_gradido_gradido_transfer_t *transfer_p;
};

/**
 * Message proto.gradido.GradidoTimeoutDeferredTransfer.
 */
struct proto_gradido_gradido_timeout_deferred_transfer_repeated_t {
    int length;
    struct proto_gradido_gradido_timeout_deferred_transfer_t *items_p;
};

struct proto_gradido_gradido_timeout_deferred_transfer_t {
    struct pbtools_message_base_t base;
    uint64_t deferred_transfer_transaction_nr;
};

int proto_gradido_gradido_transfer_sender_alloc(
    struct proto_gradido_gradido_transfer_t *self_p);

/**
 * Encoding and decoding of proto.gradido.GradidoTransfer.
 */
struct proto_gradido_gradido_transfer_t *
proto_gradido_gradido_transfer_new(
    void *workspace_p,
    size_t size);

int proto_gradido_gradido_transfer_encode(
    struct proto_gradido_gradido_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_transfer_decode(
    struct proto_gradido_gradido_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_deferred_transfer_transfer_alloc(
    struct proto_gradido_gradido_deferred_transfer_t *self_p);

int proto_gradido_gradido_deferred_transfer_timeout_duration_alloc(
    struct proto_gradido_gradido_deferred_transfer_t *self_p);

/**
 * Encoding and decoding of proto.gradido.GradidoDeferredTransfer.
 */
struct proto_gradido_gradido_deferred_transfer_t *
proto_gradido_gradido_deferred_transfer_new(
    void *workspace_p,
    size_t size);

int proto_gradido_gradido_deferred_transfer_encode(
    struct proto_gradido_gradido_deferred_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_deferred_transfer_decode(
    struct proto_gradido_gradido_deferred_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_redeem_deferred_transfer_transfer_alloc(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p);

/**
 * Encoding and decoding of proto.gradido.GradidoRedeemDeferredTransfer.
 */
struct proto_gradido_gradido_redeem_deferred_transfer_t *
proto_gradido_gradido_redeem_deferred_transfer_new(
    void *workspace_p,
    size_t size);

int proto_gradido_gradido_redeem_deferred_transfer_encode(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_redeem_deferred_transfer_decode(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.GradidoTimeoutDeferredTransfer.
 */
struct proto_gradido_gradido_timeout_deferred_transfer_t *
proto_gradido_gradido_timeout_deferred_transfer_new(
    void *workspace_p,
    size_t size);

int proto_gradido_gradido_timeout_deferred_transfer_encode(
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_gradido_timeout_deferred_transfer_decode(
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void proto_gradido_gradido_transfer_init(
    struct proto_gradido_gradido_transfer_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_gradido_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_transfer_t *self_p);

void proto_gradido_gradido_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_transfer_t *self_p);

void proto_gradido_gradido_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_deferred_transfer_init(
    struct proto_gradido_gradido_deferred_transfer_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_gradido_deferred_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_deferred_transfer_t *self_p);

void proto_gradido_gradido_deferred_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_deferred_transfer_t *self_p);

void proto_gradido_gradido_deferred_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_deferred_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_deferred_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_deferred_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_redeem_deferred_transfer_init(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_gradido_redeem_deferred_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p);

void proto_gradido_gradido_redeem_deferred_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p);

void proto_gradido_gradido_redeem_deferred_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_redeem_deferred_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_redeem_deferred_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_redeem_deferred_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_timeout_deferred_transfer_init(
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_gradido_timeout_deferred_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p);

void proto_gradido_gradido_timeout_deferred_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p);

void proto_gradido_gradido_timeout_deferred_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_timeout_deferred_transfer_repeated_t *repeated_p);

void proto_gradido_gradido_timeout_deferred_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_timeout_deferred_transfer_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
