/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef HIERO_BASIC_TYPES_H
#define HIERO_BASIC_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"
#include "basic_types.h"

/**
 * Enum proto.gradido.AccountID.account.
 */
enum proto_gradido_account_id_account_e {
    proto_gradido_account_id_account_none_e = 0,
    proto_gradido_account_id_account_account_num_e = 1,
    proto_gradido_account_id_account_alias_e = 2
};

/**
 * Message proto.gradido.AccountID.
 */
struct proto_gradido_account_id_repeated_t {
    int length;
    struct proto_gradido_account_id_t *items_p;
};

struct proto_gradido_account_id_t {
    struct pbtools_message_base_t base;
    int64_t shard_num;
    int64_t realm_num;
    enum proto_gradido_account_id_account_e account;
    union {
        int64_t account_num;
        struct pbtools_bytes_t alias;
    };
};

/**
 * Message proto.gradido.TopicID.
 */
struct proto_gradido_topic_id_repeated_t {
    int length;
    struct proto_gradido_topic_id_t *items_p;
};

struct proto_gradido_topic_id_t {
    struct pbtools_message_base_t base;
    int64_t shard_num;
    int64_t realm_num;
    int64_t topic_num;
};

/**
 * Message proto.gradido.TransactionID.
 */
struct proto_gradido_transaction_id_repeated_t {
    int length;
    struct proto_gradido_transaction_id_t *items_p;
};

struct proto_gradido_transaction_id_t {
    struct pbtools_message_base_t base;
    struct proto_gradido_timestamp_t *transaction_valid_start_p;
    struct proto_gradido_account_id_t *account_id_p;
    bool scheduled;
    int32_t nonce;
};

void proto_gradido_account_id_account_num_init(
    struct proto_gradido_account_id_t *self_p);

void proto_gradido_account_id_alias_init(
    struct proto_gradido_account_id_t *self_p);

/**
 * Encoding and decoding of proto.gradido.AccountID.
 */
struct proto_gradido_account_id_t *
proto_gradido_account_id_new(
    void *workspace_p,
    size_t size);

int proto_gradido_account_id_encode(
    struct proto_gradido_account_id_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_account_id_decode(
    struct proto_gradido_account_id_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/**
 * Encoding and decoding of proto.gradido.TopicID.
 */
struct proto_gradido_topic_id_t *
proto_gradido_topic_id_new(
    void *workspace_p,
    size_t size);

int proto_gradido_topic_id_encode(
    struct proto_gradido_topic_id_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_topic_id_decode(
    struct proto_gradido_topic_id_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

int proto_gradido_transaction_id_transaction_valid_start_alloc(
    struct proto_gradido_transaction_id_t *self_p);

int proto_gradido_transaction_id_account_id_alloc(
    struct proto_gradido_transaction_id_t *self_p);

/**
 * Encoding and decoding of proto.gradido.TransactionID.
 */
struct proto_gradido_transaction_id_t *
proto_gradido_transaction_id_new(
    void *workspace_p,
    size_t size);

int proto_gradido_transaction_id_encode(
    struct proto_gradido_transaction_id_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_transaction_id_decode(
    struct proto_gradido_transaction_id_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void proto_gradido_account_id_init(
    struct proto_gradido_account_id_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_account_id_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_account_id_t *self_p);

void proto_gradido_account_id_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_account_id_t *self_p);

void proto_gradido_account_id_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_account_id_repeated_t *repeated_p);

void proto_gradido_account_id_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_account_id_repeated_t *repeated_p);

void proto_gradido_topic_id_init(
    struct proto_gradido_topic_id_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_topic_id_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_topic_id_t *self_p);

void proto_gradido_topic_id_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_topic_id_t *self_p);

void proto_gradido_topic_id_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_topic_id_repeated_t *repeated_p);

void proto_gradido_topic_id_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_topic_id_repeated_t *repeated_p);

void proto_gradido_transaction_id_init(
    struct proto_gradido_transaction_id_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_transaction_id_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_transaction_id_t *self_p);

void proto_gradido_transaction_id_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_transaction_id_t *self_p);

void proto_gradido_transaction_id_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_transaction_id_repeated_t *repeated_p);

void proto_gradido_transaction_id_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_transaction_id_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
