/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef REGISTER_ADDRESS_H
#define REGISTER_ADDRESS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"

/**
 * Enum proto.gradido.RegisterAddress.AddressType.
 */
enum proto_gradido_register_address_address_type_e {
    proto_gradido_register_address_none_e = 0,
    proto_gradido_register_address_community_human_e = 1,
    proto_gradido_register_address_community_gmw_e = 2,
    proto_gradido_register_address_community_auf_e = 3,
    proto_gradido_register_address_community_project_e = 4,
    proto_gradido_register_address_subaccount_e = 5,
    proto_gradido_register_address_crypto_account_e = 6
};

/**
 * Message proto.gradido.RegisterAddress.
 */
struct proto_gradido_register_address_repeated_t {
    int length;
    struct proto_gradido_register_address_t *items_p;
};

struct proto_gradido_register_address_t {
    struct pbtools_message_base_t base;
    struct pbtools_bytes_t user_pubkey;
    enum proto_gradido_register_address_address_type_e address_type;
    struct pbtools_bytes_t name_hash;
    struct pbtools_bytes_t account_pubkey;
    uint32_t derivation_index;
};

/**
 * Encoding and decoding of proto.gradido.RegisterAddress.
 */
struct proto_gradido_register_address_t *
proto_gradido_register_address_new(
    void *workspace_p,
    size_t size);

int proto_gradido_register_address_encode(
    struct proto_gradido_register_address_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_register_address_decode(
    struct proto_gradido_register_address_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void proto_gradido_register_address_init(
    struct proto_gradido_register_address_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_register_address_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_register_address_t *self_p);

void proto_gradido_register_address_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_register_address_t *self_p);

void proto_gradido_register_address_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_register_address_repeated_t *repeated_p);

void proto_gradido_register_address_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_register_address_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
