/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#ifndef TRANSACTION_BODY_H
#define TRANSACTION_BODY_H

#ifdef __cplusplus
extern "C" {
#endif

#include "pbtools.h"
#include "basic_types.h"
#include "gradido_transfer.h"
#include "gradido_creation.h"
#include "community_friends_update.h"
#include "register_address.h"
#include "community_root.h"

/**
 * Enum proto.gradido.TransactionBody.CrossGroupType.
 */
enum proto_gradido_transaction_body_cross_group_type_e {
    proto_gradido_transaction_body_local_e = 0,
    proto_gradido_transaction_body_inbound_e = 1,
    proto_gradido_transaction_body_outbound_e = 2,
    proto_gradido_transaction_body_cross_e = 3
};

/**
 * Enum proto.gradido.TransactionBody.data.
 */
enum proto_gradido_transaction_body_data_e {
    proto_gradido_transaction_body_data_none_e = 0,
    proto_gradido_transaction_body_data_transfer_e = 1,
    proto_gradido_transaction_body_data_creation_e = 2,
    proto_gradido_transaction_body_data_community_friends_update_e = 3,
    proto_gradido_transaction_body_data_register_address_e = 4,
    proto_gradido_transaction_body_data_deferred_transfer_e = 5,
    proto_gradido_transaction_body_data_community_root_e = 6,
    proto_gradido_transaction_body_data_redeem_deferred_transfer_e = 7,
    proto_gradido_transaction_body_data_timeout_deferred_transfer_e = 8
};

/**
 * Message proto.gradido.TransactionBody.
 */
struct proto_gradido_transaction_body_repeated_t {
    int length;
    struct proto_gradido_transaction_body_t *items_p;
};

struct proto_gradido_transaction_body_t {
    struct pbtools_message_base_t base;
    struct proto_gradido_encrypted_memo_repeated_t memos;
    struct proto_gradido_timestamp_t *created_at_p;
    uint32_t version_number;
    enum proto_gradido_transaction_body_cross_group_type_e type;
    struct pbtools_bytes_t other_community_uuid;
    enum proto_gradido_transaction_body_data_e data;
    union {
        struct proto_gradido_gradido_transfer_t *transfer_p;
        struct proto_gradido_gradido_creation_t *creation_p;
        struct proto_gradido_community_friends_update_t *community_friends_update_p;
        struct proto_gradido_register_address_t *register_address_p;
        struct proto_gradido_gradido_deferred_transfer_t *deferred_transfer_p;
        struct proto_gradido_community_root_t *community_root_p;
        struct proto_gradido_gradido_redeem_deferred_transfer_t *redeem_deferred_transfer_p;
        struct proto_gradido_gradido_timeout_deferred_transfer_t *timeout_deferred_transfer_p;
    };
};

int proto_gradido_transaction_body_memos_alloc(
    struct proto_gradido_transaction_body_t *self_p,
    int length);

int proto_gradido_transaction_body_created_at_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_creation_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_community_friends_update_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_register_address_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_deferred_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_community_root_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_redeem_deferred_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p);

int proto_gradido_transaction_body_timeout_deferred_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p);

/**
 * Encoding and decoding of proto.gradido.TransactionBody.
 */
struct proto_gradido_transaction_body_t *
proto_gradido_transaction_body_new(
    void *workspace_p,
    size_t size);

int proto_gradido_transaction_body_encode(
    struct proto_gradido_transaction_body_t *self_p,
    uint8_t *encoded_p,
    size_t size);

int proto_gradido_transaction_body_decode(
    struct proto_gradido_transaction_body_t *self_p,
    const uint8_t *encoded_p,
    size_t size);

/* Internal functions. Do not use! */

void proto_gradido_transaction_body_init(
    struct proto_gradido_transaction_body_t *self_p,
    struct pbtools_heap_t *heap_p);

void proto_gradido_transaction_body_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_transaction_body_t *self_p);

void proto_gradido_transaction_body_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_transaction_body_t *self_p);

void proto_gradido_transaction_body_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_transaction_body_repeated_t *repeated_p);

void proto_gradido_transaction_body_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_transaction_body_repeated_t *repeated_p);

#ifdef __cplusplus
}
#endif

#endif
