<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/BasicTypes.proto

namespace GPBMetadata\Gradido;

class BasicTypes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
À
gradido/BasicTypes.protoproto.gradido"
Key
ed25519 ("2
SignaturePair
pubKey (
	signature ("=
SignatureMap-
sigPair (2.proto.gradido.SignaturePair"+
	Timestamp
seconds (
nanos ("#
TimestampSeconds
seconds ("0
TransferAmount
pubkey (
amount (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

