<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GlobalGroupAdd.proto

namespace GPBMetadata\Gradido;

class GlobalGroupAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Œ
gradido/GlobalGroupAdd.protoproto.gradido"U
GlobalGroupAdd

group_name (	
group_alias (	
parent_group_alias (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

