<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoCreation.proto

namespace GPBMetadata\Gradido;

class GradidoCreation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            '
±
gradido/GradidoCreation.protoproto.gradido"y
GradidoCreation0
	recipiant (2.proto.gradido.TransferAmount4
target_date (2.proto.gradido.TimestampSecondsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

