<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GroupMemberUpdate.proto

namespace GPBMetadata\Gradido;

class GroupMemberUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad2020a1f6772616469646f2f47726f75704d656d626572557064617465" .
            "2e70726f746f120d70726f746f2e6772616469646f2297020a1147726f75" .
            "704d656d62657255706461746512130a0b757365725f7075626b65791801" .
            "2001280c124d0a126d656d6265725f7570646174655f7479706518022001" .
            "280e32312e70726f746f2e6772616469646f2e47726f75704d656d626572" .
            "5570646174652e4d656d6265725570646174655479706512370a15706169" .
            "7265645f7472616e73616374696f6e5f696418032001280b32182e70726f" .
            "746f2e6772616469646f2e54696d657374616d7012140a0c746172676574" .
            "5f67726f7570180420012809224f0a104d656d6265725570646174655479" .
            "7065120c0a084144445f55534552100012150a114d4f56455f555345525f" .
            "494e424f554e44100112160a124d4f56455f555345525f4f5554424f554e" .
            "441002620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

