<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GroupFriendsUpdate.proto

namespace GPBMetadata\Gradido;

class GroupFriendsUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6010a206772616469646f2f47726f7570467269656e64735570646174" .
            "652e70726f746f120d70726f746f2e6772616469646f228a010a1247726f" .
            "7570467269656e6473557064617465120d0a0567726f7570180120012809" .
            "12380a06616374696f6e18022001280e32282e70726f746f2e6772616469" .
            "646f2e47726f7570467269656e64735570646174652e416374696f6e222b" .
            "0a06416374696f6e120e0a0a4144445f465249454e44100012110a0d5245" .
            "4d4f56455f465249454e441001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

