<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/ManageNodeGroupAdd.proto

namespace GPBMetadata\Gradido;

class ManageNodeGroupAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa010a206772616469646f2f4d616e6167654e6f646547726f75704164" .
            "642e70726f746f120d70726f746f2e6772616469646f226f0a124d616e61" .
            "67654e6f646547726f757041646412120a0a67726f75705f6e616d651801" .
            "2001280912130a0b67726f75705f616c69617318022001280912300a0f68" .
            "65646572615f746f7069635f696418032001280b32172e70726f746f2e67" .
            "72616469646f2e4865646572614944620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

