<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/ManageNodeRequest.proto

namespace GPBMetadata\Gradido;

class ManageNodeRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(
            '
è
gradido/ManageNodeRequest.protoproto.gradido"U
ManageNodeRequest,
sig_map (2.proto.gradido.SignatureMap

body_bytes (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

