<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/ManageNodeRequest.proto

namespace GPBMetadata\Gradido;

class ManageNodeRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade020a1f6772616469646f2f4d616e6167654e6f646552657175657374" .
            "2e70726f746f120d70726f746f2e6772616469646f22550a114d616e6167" .
            "654e6f646552657175657374122c0a077369675f6d617018012001280b32" .
            "1b2e70726f746f2e6772616469646f2e5369676e61747572654d61701212" .
            "0a0a626f64795f627974657318022001280c22cc010a124d616e6167654e" .
            "6f6465526573706f6e7365120f0a0773756363657373180120012808123a" .
            "0a056572726f7218022001280e322b2e70726f746f2e6772616469646f2e" .
            "4d616e6167654e6f6465526573706f6e73652e4572726f72436f64652269" .
            "0a094572726f72436f646512100a0c494e56414c49445f424f4459100012" .
            "150a11494e56414c49445f5349474e4154555245100112140a105349474e" .
            "45525f4e4f545f4b4e4f574e1002121d0a1947524f55505f414c4941535f" .
            "414c52454144595f45584953541003620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

