<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/ManageNodeBody.proto

namespace GPBMetadata\Gradido;

class ManageNodeBody
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\ManageNodeGroupAdd::initOnce();
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9010a1c6772616469646f2f4d616e6167654e6f6465426f64792e7072" .
            "6f746f120d70726f746f2e6772616469646f1a186772616469646f2f4261" .
            "73696354797065732e70726f746f22680a0e4d616e6167654e6f6465426f" .
            "647912160a0e76657273696f6e5f6e756d62657218012001280412360a09" .
            "67726f75705f61646418032001280b32212e70726f746f2e677261646964" .
            "6f2e4d616e6167654e6f646547726f7570416464480042060a0464617461" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

