<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/TransactionBody.proto

namespace GPBMetadata\Gradido;

class TransactionBody
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Gradido\GradidoTransfer::initOnce();
        \GPBMetadata\Gradido\GradidoCreation::initOnce();
        \GPBMetadata\Gradido\GroupFriendsUpdate::initOnce();
        \GPBMetadata\Gradido\GroupMemberUpdate::initOnce();
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92040a1d6772616469646f2f5472616e73616374696f6e426f64792e70" .
            "726f746f120d70726f746f2e6772616469646f1a1d6772616469646f2f47" .
            "72616469646f4372656174696f6e2e70726f746f1a206772616469646f2f" .
            "47726f7570467269656e64735570646174652e70726f746f1a1f67726164" .
            "69646f2f47726f75704d656d6265725570646174652e70726f746f1a1867" .
            "72616469646f2f426173696354797065732e70726f746f22dd020a0f5472" .
            "616e73616374696f6e426f6479120c0a046d656d6f18012001280912300a" .
            "076372656174656418022001280b321f2e70726f746f2e6772616469646f" .
            "2e54696d657374616d705365636f6e647312160a0e76657273696f6e5f6e" .
            "756d62657218032001280412320a087472616e7366657218062001280b32" .
            "1e2e70726f746f2e6772616469646f2e4772616469646f5472616e736665" .
            "72480012320a086372656174696f6e18072001280b321e2e70726f746f2e" .
            "6772616469646f2e4772616469646f4372656174696f6e480012410a1467" .
            "726f75705f667269656e64735f75706461746518082001280b32212e7072" .
            "6f746f2e6772616469646f2e47726f7570467269656e6473557064617465" .
            "4800123f0a1367726f75705f6d656d6265725f7570646174651809200128" .
            "0b32202e70726f746f2e6772616469646f2e47726f75704d656d62657255" .
            "7064617465480042060a0464617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

