<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BasicTypes.proto

namespace Model\Messages\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.messages.gradido.SignatureMap</code>
 */
final class SignatureMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Each signature pair corresponds to a unique Key required to sign the transaction.
     *
     * Generated from protobuf field <code>repeated .model.messages.gradido.SignaturePair sigPair = 1;</code>
     */
    private $sigPair;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Model\Messages\Gradido\SignaturePair[]|\Google\Protobuf\Internal\RepeatedField $sigPair
     *           Each signature pair corresponds to a unique Key required to sign the transaction.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BasicTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Each signature pair corresponds to a unique Key required to sign the transaction.
     *
     * Generated from protobuf field <code>repeated .model.messages.gradido.SignaturePair sigPair = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSigPair()
    {
        return $this->sigPair;
    }

    /**
     * Each signature pair corresponds to a unique Key required to sign the transaction.
     *
     * Generated from protobuf field <code>repeated .model.messages.gradido.SignaturePair sigPair = 1;</code>
     * @param \Model\Messages\Gradido\SignaturePair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSigPair($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Model\Messages\Gradido\SignaturePair::class);
        $this->sigPair = $arr;

        return $this;
    }

}

