<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transaction.proto

namespace Model\Messages\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.messages.gradido.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>.model.messages.gradido.TimestampSeconds received = 2;</code>
     */
    private $received = null;
    /**
     * Generated from protobuf field <code>.model.messages.gradido.SignatureMap sigMap = 3;</code>
     */
    private $sigMap = null;
    /**
     * Generated from protobuf field <code>bytes txHash = 4;</code>
     */
    private $txHash = '';
    /**
     * Generated from protobuf field <code>bytes bodyBytes = 5;</code>
     */
    private $bodyBytes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type \Model\Messages\Gradido\TimestampSeconds $received
     *     @type \Model\Messages\Gradido\SignatureMap $sigMap
     *     @type string $txHash
     *     @type string $bodyBytes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.TimestampSeconds received = 2;</code>
     * @return \Model\Messages\Gradido\TimestampSeconds
     */
    public function getReceived()
    {
        return $this->received;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.TimestampSeconds received = 2;</code>
     * @param \Model\Messages\Gradido\TimestampSeconds $var
     * @return $this
     */
    public function setReceived($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\TimestampSeconds::class);
        $this->received = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.SignatureMap sigMap = 3;</code>
     * @return \Model\Messages\Gradido\SignatureMap
     */
    public function getSigMap()
    {
        return $this->sigMap;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.SignatureMap sigMap = 3;</code>
     * @param \Model\Messages\Gradido\SignatureMap $var
     * @return $this
     */
    public function setSigMap($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\SignatureMap::class);
        $this->sigMap = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 4;</code>
     * @return string
     */
    public function getTxHash()
    {
        return $this->txHash;
    }

    /**
     * Generated from protobuf field <code>bytes txHash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTxHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->txHash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bodyBytes = 5;</code>
     * @return string
     */
    public function getBodyBytes()
    {
        return $this->bodyBytes;
    }

    /**
     * Generated from protobuf field <code>bytes bodyBytes = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBodyBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->bodyBytes = $var;

        return $this;
    }

}

