<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GroupFriendsUpdate.proto

namespace Proto\Gradido;

if (false) {
    /**
     * This class is deprecated. Use Proto\Gradido\GroupFriendsUpdate\Action instead.
     * @deprecated
     */
    class GroupFriendsUpdate_Action {}
}
class_exists(GroupFriendsUpdate\Action::class);
@trigger_error('Proto\Gradido\GroupFriendsUpdate_Action is deprecated and will be removed in the next major release. Use Proto\Gradido\GroupFriendsUpdate\Action instead', E_USER_DEPRECATED);

