<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GroupMemberUpdate.proto

namespace Proto\Gradido;

if (false) {
    /**
     * This class is deprecated. Use Proto\Gradido\GroupMemberUpdate\MemberUpdateType instead.
     * @deprecated
     */
    class GroupMemberUpdate_MemberUpdateType {}
}
class_exists(GroupMemberUpdate\MemberUpdateType::class);
@trigger_error('Proto\Gradido\GroupMemberUpdate_MemberUpdateType is deprecated and will be removed in the next major release. Use Proto\Gradido\GroupMemberUpdate\MemberUpdateType instead', E_USER_DEPRECATED);

