<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/TransactionBody.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.TransactionBody</code>
 */
class TransactionBody extends \Google\Protobuf\Internal\Message
{
    /**
     * max 150 chars
     *
     * Generated from protobuf field <code>string memo = 1;</code>
     */
    private $memo = '';
    /**
     * Generated from protobuf field <code>uint64 version_number = 6;</code>
     */
    private $version_number = 0;
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $memo
     *           max 150 chars
     *     @type \Proto\Gradido\GradidoTransfer $transfer
     *     @type \Proto\Gradido\GradidoCreation $creation
     *     @type \Proto\Gradido\GroupFriendsUpdate $group_friends_update
     *     @type \Proto\Gradido\GroupMemberUpdate $group_member_update
     *     @type int|string $version_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\TransactionBody::initOnce();
        parent::__construct($data);
    }

    /**
     * max 150 chars
     *
     * Generated from protobuf field <code>string memo = 1;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * max 150 chars
     *
     * Generated from protobuf field <code>string memo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoTransfer transfer = 2;</code>
     * @return \Proto\Gradido\GradidoTransfer
     */
    public function getTransfer()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoTransfer transfer = 2;</code>
     * @param \Proto\Gradido\GradidoTransfer $var
     * @return $this
     */
    public function setTransfer($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\GradidoTransfer::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoCreation creation = 3;</code>
     * @return \Proto\Gradido\GradidoCreation
     */
    public function getCreation()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoCreation creation = 3;</code>
     * @param \Proto\Gradido\GradidoCreation $var
     * @return $this
     */
    public function setCreation($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\GradidoCreation::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GroupFriendsUpdate group_friends_update = 4;</code>
     * @return \Proto\Gradido\GroupFriendsUpdate
     */
    public function getGroupFriendsUpdate()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GroupFriendsUpdate group_friends_update = 4;</code>
     * @param \Proto\Gradido\GroupFriendsUpdate $var
     * @return $this
     */
    public function setGroupFriendsUpdate($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\GroupFriendsUpdate::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GroupMemberUpdate group_member_update = 5;</code>
     * @return \Proto\Gradido\GroupMemberUpdate
     */
    public function getGroupMemberUpdate()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GroupMemberUpdate group_member_update = 5;</code>
     * @param \Proto\Gradido\GroupMemberUpdate $var
     * @return $this
     */
    public function setGroupMemberUpdate($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\GroupMemberUpdate::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 version_number = 6;</code>
     * @return int|string
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * Generated from protobuf field <code>uint64 version_number = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

