# These file filter patterns are used by the action https://github.com/dorny/paths-filter

# more differentiated filters for admin interface, which might be used later
# admin_locales: &admin_locales
#   - 'admin/src/locales/**'
#   - 'admin/scripts/sort*'

# admin_stylelinting: &admin_stylelinting
#   - 'admin/{components,layouts,pages}/**/*.{scss,vue}'
#   - 'admin/.stylelintrc.js'

# admin_linting: &admin_linting
#   - 'admin/.eslint*'
#   - 'admin/babel.config.js'
#   - 'admin/package.json'
#   - 'admin/**/*.{js,vue}'
#   - *admin_locales

# admin_unit_testing: &admin_unit_testing
#   - 'admin/package.json'
#   - 'admin/{jest,vue}.config.js'
#   - 'admin/{public,run,test}/**/*'
#   - 'admin/src/!(locales)/**/*'

# admin_docker_building: &admin_docker_building
#   - 'admin/.dockerignore'
#   - 'admin/Dockerfile'
#   - *admin_unit_testing

admin: &admin
  - 'admin/**/*'

backend: &backend
  - 'backend/**/*'

dht_node: &dht_node
  - 'dht-node/**/*'

docker-compose: &docker-compose
  - 'docker-compose.*'

federation: &federation
  - 'federation/**/*'

frontend: &frontend
  - 'frontend/**/*'

mariadb: &mariadb
  - 'mariadb/**/*'

nginx: &nginx
  - 'nginx/**/*'