FROM gradido/login_dependencies:alpine-debug-3 as login_server_alpine_debug

ENV DOCKER_WORKDIR="/code"


EXPOSE 1200
EXPOSE 1201
WORKDIR ${DOCKER_WORKDIR}

COPY ./CMakeLists.txt.lib ./CMakeLists.txt
COPY ./scripts ./scripts
COPY ./cmake ./cmake 
RUN ln -s /usr/local/googletest ./googletest

CMD cd scripts; ./build_debug.sh; cd ..; ./build/bin/Gradido_LoginServer

