CREATE TABLE `groups` ( 
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `alias` VARCHAR(255) NOT NULL,
 `name` VARCHAR(255) NOT NULL,
 `description` TEXT NULL DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4; 