CREATE TABLE `hedera_ids` ( 
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`shardNum` BIGINT NOT NULL DEFAULT '0',
	`realmNum` BIGINT NOT NULL DEFAULT '0',
	`num` BIGINT NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4; 