CREATE TABLE `hedera_accounts` (
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `user_id` INT UNSIGNED NOT NULL,
 `account_hedera_id` INT UNSIGNED NOT NULL,
 `account_key_id` INT UNSIGNED NOT NULL,
 `balance` BIGINT UNSIGNED NOT NULL DEFAULT '0',
 `updated` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4; 
