/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "basic_types.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void proto_gradido_account_balance_init(
    struct proto_gradido_account_balance_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    pbtools_bytes_init(&self_p->pubkey);
    self_p->balance = 0;
    pbtools_bytes_init(&self_p->community_uuid);
}

void proto_gradido_account_balance_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_account_balance_t *self_p)
{
    pbtools_encoder_write_bytes(encoder_p, 3, &self_p->community_uuid);
    pbtools_encoder_write_int64(encoder_p, 2, self_p->balance);
    pbtools_encoder_write_bytes(encoder_p, 1, &self_p->pubkey);
}

void proto_gradido_account_balance_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_account_balance_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->pubkey);
            break;

        case 2:
            self_p->balance = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 3:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->community_uuid);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_account_balance_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_account_balance_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_account_balance_t),
        (pbtools_message_encode_inner_t)proto_gradido_account_balance_encode_inner);
}

void proto_gradido_account_balance_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_account_balance_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_account_balance_t),
        (pbtools_message_init_t)proto_gradido_account_balance_init,
        (pbtools_message_decode_inner_t)proto_gradido_account_balance_decode_inner);
}

struct proto_gradido_account_balance_t *
proto_gradido_account_balance_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_account_balance_t),
                (pbtools_message_init_t)proto_gradido_account_balance_init));
}

int proto_gradido_account_balance_encode(
    struct proto_gradido_account_balance_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_account_balance_encode_inner));
}

int proto_gradido_account_balance_decode(
    struct proto_gradido_account_balance_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_account_balance_decode_inner));
}

void proto_gradido_duration_seconds_init(
    struct proto_gradido_duration_seconds_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->seconds = 0;
}

void proto_gradido_duration_seconds_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_duration_seconds_t *self_p)
{
    pbtools_encoder_write_uint64(encoder_p, 1, self_p->seconds);
}

void proto_gradido_duration_seconds_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_duration_seconds_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->seconds = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_duration_seconds_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_duration_seconds_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_duration_seconds_t),
        (pbtools_message_encode_inner_t)proto_gradido_duration_seconds_encode_inner);
}

void proto_gradido_duration_seconds_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_duration_seconds_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_duration_seconds_t),
        (pbtools_message_init_t)proto_gradido_duration_seconds_init,
        (pbtools_message_decode_inner_t)proto_gradido_duration_seconds_decode_inner);
}

struct proto_gradido_duration_seconds_t *
proto_gradido_duration_seconds_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_duration_seconds_t),
                (pbtools_message_init_t)proto_gradido_duration_seconds_init));
}

int proto_gradido_duration_seconds_encode(
    struct proto_gradido_duration_seconds_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_duration_seconds_encode_inner));
}

int proto_gradido_duration_seconds_decode(
    struct proto_gradido_duration_seconds_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_duration_seconds_decode_inner));
}

void proto_gradido_encrypted_memo_init(
    struct proto_gradido_encrypted_memo_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->type = 0;
    pbtools_bytes_init(&self_p->memo);
}

void proto_gradido_encrypted_memo_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_encrypted_memo_t *self_p)
{
    pbtools_encoder_write_bytes(encoder_p, 2, &self_p->memo);
    pbtools_encoder_write_enum(encoder_p, 1, self_p->type);
}

void proto_gradido_encrypted_memo_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_encrypted_memo_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->type = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        case 2:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->memo);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_encrypted_memo_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_encrypted_memo_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_encrypted_memo_t),
        (pbtools_message_encode_inner_t)proto_gradido_encrypted_memo_encode_inner);
}

void proto_gradido_encrypted_memo_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_encrypted_memo_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_encrypted_memo_t),
        (pbtools_message_init_t)proto_gradido_encrypted_memo_init,
        (pbtools_message_decode_inner_t)proto_gradido_encrypted_memo_decode_inner);
}

struct proto_gradido_encrypted_memo_t *
proto_gradido_encrypted_memo_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_encrypted_memo_t),
                (pbtools_message_init_t)proto_gradido_encrypted_memo_init));
}

int proto_gradido_encrypted_memo_encode(
    struct proto_gradido_encrypted_memo_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_encrypted_memo_encode_inner));
}

int proto_gradido_encrypted_memo_decode(
    struct proto_gradido_encrypted_memo_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_encrypted_memo_decode_inner));
}

void proto_gradido_signature_pair_init(
    struct proto_gradido_signature_pair_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    pbtools_bytes_init(&self_p->pubkey);
    pbtools_bytes_init(&self_p->signature);
}

void proto_gradido_signature_pair_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_signature_pair_t *self_p)
{
    pbtools_encoder_write_bytes(encoder_p, 2, &self_p->signature);
    pbtools_encoder_write_bytes(encoder_p, 1, &self_p->pubkey);
}

void proto_gradido_signature_pair_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_signature_pair_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->pubkey);
            break;

        case 2:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->signature);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_signature_pair_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_signature_pair_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_signature_pair_t),
        (pbtools_message_encode_inner_t)proto_gradido_signature_pair_encode_inner);
}

void proto_gradido_signature_pair_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_signature_pair_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_signature_pair_t),
        (pbtools_message_init_t)proto_gradido_signature_pair_init,
        (pbtools_message_decode_inner_t)proto_gradido_signature_pair_decode_inner);
}

struct proto_gradido_signature_pair_t *
proto_gradido_signature_pair_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_signature_pair_t),
                (pbtools_message_init_t)proto_gradido_signature_pair_init));
}

int proto_gradido_signature_pair_encode(
    struct proto_gradido_signature_pair_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_signature_pair_encode_inner));
}

int proto_gradido_signature_pair_decode(
    struct proto_gradido_signature_pair_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_signature_pair_decode_inner));
}

void proto_gradido_signature_map_init(
    struct proto_gradido_signature_map_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->sig_pair.length = 0;
}

void proto_gradido_signature_map_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_signature_map_t *self_p)
{
    proto_gradido_signature_pair_encode_repeated_inner(
        encoder_p,
        1,
        &self_p->sig_pair);
}

void proto_gradido_signature_map_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_signature_map_t *self_p)
{
    int wire_type;
    struct pbtools_repeated_info_t repeated_info_sig_pair;

    pbtools_repeated_info_init(&repeated_info_sig_pair, 1);

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_repeated_info_decode(&repeated_info_sig_pair,
                                         decoder_p,
                                         wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }

    proto_gradido_signature_pair_decode_repeated_inner(
        decoder_p,
        &repeated_info_sig_pair,
        &self_p->sig_pair);
}

int proto_gradido_signature_map_sig_pair_alloc(
    struct proto_gradido_signature_map_t *self_p,
    int length)
{
    return (pbtools_alloc_repeated(
                (struct pbtools_repeated_message_t *)&self_p->sig_pair,
                length,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_signature_pair_t),
                (pbtools_message_init_t)proto_gradido_signature_pair_init));
}

void proto_gradido_signature_map_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_signature_map_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_signature_map_t),
        (pbtools_message_encode_inner_t)proto_gradido_signature_map_encode_inner);
}

void proto_gradido_signature_map_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_signature_map_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_signature_map_t),
        (pbtools_message_init_t)proto_gradido_signature_map_init,
        (pbtools_message_decode_inner_t)proto_gradido_signature_map_decode_inner);
}

struct proto_gradido_signature_map_t *
proto_gradido_signature_map_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_signature_map_t),
                (pbtools_message_init_t)proto_gradido_signature_map_init));
}

int proto_gradido_signature_map_encode(
    struct proto_gradido_signature_map_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_signature_map_encode_inner));
}

int proto_gradido_signature_map_decode(
    struct proto_gradido_signature_map_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_signature_map_decode_inner));
}

void proto_gradido_timestamp_init(
    struct proto_gradido_timestamp_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->seconds = 0;
    self_p->nanos = 0;
}

void proto_gradido_timestamp_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_timestamp_t *self_p)
{
    pbtools_encoder_write_int32(encoder_p, 2, self_p->nanos);
    pbtools_encoder_write_int64(encoder_p, 1, self_p->seconds);
}

void proto_gradido_timestamp_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_timestamp_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->seconds = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 2:
            self_p->nanos = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_timestamp_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_timestamp_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_timestamp_t),
        (pbtools_message_encode_inner_t)proto_gradido_timestamp_encode_inner);
}

void proto_gradido_timestamp_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_timestamp_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_timestamp_t),
        (pbtools_message_init_t)proto_gradido_timestamp_init,
        (pbtools_message_decode_inner_t)proto_gradido_timestamp_decode_inner);
}

struct proto_gradido_timestamp_t *
proto_gradido_timestamp_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init));
}

int proto_gradido_timestamp_encode(
    struct proto_gradido_timestamp_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_timestamp_encode_inner));
}

int proto_gradido_timestamp_decode(
    struct proto_gradido_timestamp_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_timestamp_decode_inner));
}

void proto_gradido_timestamp_seconds_init(
    struct proto_gradido_timestamp_seconds_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->seconds = 0;
}

void proto_gradido_timestamp_seconds_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_timestamp_seconds_t *self_p)
{
    pbtools_encoder_write_int64(encoder_p, 1, self_p->seconds);
}

void proto_gradido_timestamp_seconds_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_timestamp_seconds_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->seconds = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_timestamp_seconds_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_timestamp_seconds_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_timestamp_seconds_t),
        (pbtools_message_encode_inner_t)proto_gradido_timestamp_seconds_encode_inner);
}

void proto_gradido_timestamp_seconds_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_timestamp_seconds_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_timestamp_seconds_t),
        (pbtools_message_init_t)proto_gradido_timestamp_seconds_init,
        (pbtools_message_decode_inner_t)proto_gradido_timestamp_seconds_decode_inner);
}

struct proto_gradido_timestamp_seconds_t *
proto_gradido_timestamp_seconds_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_timestamp_seconds_t),
                (pbtools_message_init_t)proto_gradido_timestamp_seconds_init));
}

int proto_gradido_timestamp_seconds_encode(
    struct proto_gradido_timestamp_seconds_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_timestamp_seconds_encode_inner));
}

int proto_gradido_timestamp_seconds_decode(
    struct proto_gradido_timestamp_seconds_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_timestamp_seconds_decode_inner));
}

void proto_gradido_transfer_amount_init(
    struct proto_gradido_transfer_amount_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    pbtools_bytes_init(&self_p->pubkey);
    self_p->amount = 0;
    pbtools_bytes_init(&self_p->community_uuid);
}

void proto_gradido_transfer_amount_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_transfer_amount_t *self_p)
{
    pbtools_encoder_write_bytes(encoder_p, 3, &self_p->community_uuid);
    pbtools_encoder_write_int64(encoder_p, 2, self_p->amount);
    pbtools_encoder_write_bytes(encoder_p, 1, &self_p->pubkey);
}

void proto_gradido_transfer_amount_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_transfer_amount_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->pubkey);
            break;

        case 2:
            self_p->amount = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 3:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->community_uuid);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_transfer_amount_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_transfer_amount_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_transfer_amount_t),
        (pbtools_message_encode_inner_t)proto_gradido_transfer_amount_encode_inner);
}

void proto_gradido_transfer_amount_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_transfer_amount_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_transfer_amount_t),
        (pbtools_message_init_t)proto_gradido_transfer_amount_init,
        (pbtools_message_decode_inner_t)proto_gradido_transfer_amount_decode_inner);
}

struct proto_gradido_transfer_amount_t *
proto_gradido_transfer_amount_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_transfer_amount_t),
                (pbtools_message_init_t)proto_gradido_transfer_amount_init));
}

int proto_gradido_transfer_amount_encode(
    struct proto_gradido_transfer_amount_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_transfer_amount_encode_inner));
}

int proto_gradido_transfer_amount_decode(
    struct proto_gradido_transfer_amount_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_transfer_amount_decode_inner));
}
