/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "confirmed_transaction.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void proto_gradido_confirmed_transaction_init(
    struct proto_gradido_confirmed_transaction_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->id = 0;
    self_p->transaction_p = NULL;
    self_p->confirmed_at_p = NULL;
    self_p->version_number = 0;
    pbtools_bytes_init(&self_p->running_hash);
    self_p->ledger_anchor_p = NULL;
    self_p->account_balances.length = 0;
    self_p->balance_derivation = 0;
}

void proto_gradido_confirmed_transaction_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_confirmed_transaction_t *self_p)
{
    pbtools_encoder_write_enum(encoder_p, 8, self_p->balance_derivation);
    proto_gradido_account_balance_encode_repeated_inner(
        encoder_p,
        7,
        &self_p->account_balances);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        6,
        (struct pbtools_message_base_t *)self_p->ledger_anchor_p,
        (pbtools_message_encode_inner_t)proto_gradido_ledger_anchor_encode_inner);
    pbtools_encoder_write_bytes(encoder_p, 5, &self_p->running_hash);
    pbtools_encoder_write_uint32(encoder_p, 4, self_p->version_number);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        3,
        (struct pbtools_message_base_t *)self_p->confirmed_at_p,
        (pbtools_message_encode_inner_t)proto_gradido_timestamp_encode_inner);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        2,
        (struct pbtools_message_base_t *)self_p->transaction_p,
        (pbtools_message_encode_inner_t)proto_gradido_gradido_transaction_encode_inner);
    pbtools_encoder_write_uint64(encoder_p, 1, self_p->id);
}

void proto_gradido_confirmed_transaction_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_confirmed_transaction_t *self_p)
{
    int wire_type;
    struct pbtools_repeated_info_t repeated_info_account_balances;

    pbtools_repeated_info_init(&repeated_info_account_balances, 7);

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->id = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        case 2:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->transaction_p,
                sizeof(struct proto_gradido_gradido_transaction_t),
                (pbtools_message_init_t)proto_gradido_gradido_transaction_init,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_transaction_decode_inner);
            break;

        case 3:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->confirmed_at_p,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init,
                (pbtools_message_decode_inner_t)proto_gradido_timestamp_decode_inner);
            break;

        case 4:
            self_p->version_number = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 5:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->running_hash);
            break;

        case 6:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->ledger_anchor_p,
                sizeof(struct proto_gradido_ledger_anchor_t),
                (pbtools_message_init_t)proto_gradido_ledger_anchor_init,
                (pbtools_message_decode_inner_t)proto_gradido_ledger_anchor_decode_inner);
            break;

        case 7:
            pbtools_repeated_info_decode(&repeated_info_account_balances,
                                         decoder_p,
                                         wire_type);
            break;

        case 8:
            self_p->balance_derivation = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }

    proto_gradido_account_balance_decode_repeated_inner(
        decoder_p,
        &repeated_info_account_balances,
        &self_p->account_balances);
}

int proto_gradido_confirmed_transaction_transaction_alloc(
    struct proto_gradido_confirmed_transaction_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->transaction_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_transaction_t),
                (pbtools_message_init_t)proto_gradido_gradido_transaction_init));
}

int proto_gradido_confirmed_transaction_confirmed_at_alloc(
    struct proto_gradido_confirmed_transaction_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->confirmed_at_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init));
}

int proto_gradido_confirmed_transaction_ledger_anchor_alloc(
    struct proto_gradido_confirmed_transaction_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->ledger_anchor_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_ledger_anchor_t),
                (pbtools_message_init_t)proto_gradido_ledger_anchor_init));
}

int proto_gradido_confirmed_transaction_account_balances_alloc(
    struct proto_gradido_confirmed_transaction_t *self_p,
    int length)
{
    return (pbtools_alloc_repeated(
                (struct pbtools_repeated_message_t *)&self_p->account_balances,
                length,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_account_balance_t),
                (pbtools_message_init_t)proto_gradido_account_balance_init));
}

void proto_gradido_confirmed_transaction_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_confirmed_transaction_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_confirmed_transaction_t),
        (pbtools_message_encode_inner_t)proto_gradido_confirmed_transaction_encode_inner);
}

void proto_gradido_confirmed_transaction_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_confirmed_transaction_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_confirmed_transaction_t),
        (pbtools_message_init_t)proto_gradido_confirmed_transaction_init,
        (pbtools_message_decode_inner_t)proto_gradido_confirmed_transaction_decode_inner);
}

struct proto_gradido_confirmed_transaction_t *
proto_gradido_confirmed_transaction_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_confirmed_transaction_t),
                (pbtools_message_init_t)proto_gradido_confirmed_transaction_init));
}

int proto_gradido_confirmed_transaction_encode(
    struct proto_gradido_confirmed_transaction_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_confirmed_transaction_encode_inner));
}

int proto_gradido_confirmed_transaction_decode(
    struct proto_gradido_confirmed_transaction_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_confirmed_transaction_decode_inner));
}
