/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "gradido_transfer.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void proto_gradido_gradido_transfer_init(
    struct proto_gradido_gradido_transfer_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->sender_p = NULL;
    pbtools_bytes_init(&self_p->recipient);
}

void proto_gradido_gradido_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_transfer_t *self_p)
{
    pbtools_encoder_write_bytes(encoder_p, 2, &self_p->recipient);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        1,
        (struct pbtools_message_base_t *)self_p->sender_p,
        (pbtools_message_encode_inner_t)proto_gradido_transfer_amount_encode_inner);
}

void proto_gradido_gradido_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_transfer_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->sender_p,
                sizeof(struct proto_gradido_transfer_amount_t),
                (pbtools_message_init_t)proto_gradido_transfer_amount_init,
                (pbtools_message_decode_inner_t)proto_gradido_transfer_amount_decode_inner);
            break;

        case 2:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->recipient);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int proto_gradido_gradido_transfer_sender_alloc(
    struct proto_gradido_gradido_transfer_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->sender_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_transfer_amount_t),
                (pbtools_message_init_t)proto_gradido_transfer_amount_init));
}

void proto_gradido_gradido_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_transfer_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_transfer_t),
        (pbtools_message_encode_inner_t)proto_gradido_gradido_transfer_encode_inner);
}

void proto_gradido_gradido_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_transfer_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_transfer_decode_inner);
}

struct proto_gradido_gradido_transfer_t *
proto_gradido_gradido_transfer_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_gradido_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_transfer_init));
}

int proto_gradido_gradido_transfer_encode(
    struct proto_gradido_gradido_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_gradido_transfer_encode_inner));
}

int proto_gradido_gradido_transfer_decode(
    struct proto_gradido_gradido_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_transfer_decode_inner));
}

void proto_gradido_gradido_deferred_transfer_init(
    struct proto_gradido_gradido_deferred_transfer_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->transfer_p = NULL;
    self_p->timeout_duration_p = NULL;
}

void proto_gradido_gradido_deferred_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_deferred_transfer_t *self_p)
{
    pbtools_encoder_sub_message_encode(
        encoder_p,
        2,
        (struct pbtools_message_base_t *)self_p->timeout_duration_p,
        (pbtools_message_encode_inner_t)proto_gradido_duration_seconds_encode_inner);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        1,
        (struct pbtools_message_base_t *)self_p->transfer_p,
        (pbtools_message_encode_inner_t)proto_gradido_gradido_transfer_encode_inner);
}

void proto_gradido_gradido_deferred_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_deferred_transfer_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->transfer_p,
                sizeof(struct proto_gradido_gradido_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_transfer_init,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_transfer_decode_inner);
            break;

        case 2:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->timeout_duration_p,
                sizeof(struct proto_gradido_duration_seconds_t),
                (pbtools_message_init_t)proto_gradido_duration_seconds_init,
                (pbtools_message_decode_inner_t)proto_gradido_duration_seconds_decode_inner);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int proto_gradido_gradido_deferred_transfer_transfer_alloc(
    struct proto_gradido_gradido_deferred_transfer_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->transfer_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_transfer_init));
}

int proto_gradido_gradido_deferred_transfer_timeout_duration_alloc(
    struct proto_gradido_gradido_deferred_transfer_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->timeout_duration_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_duration_seconds_t),
                (pbtools_message_init_t)proto_gradido_duration_seconds_init));
}

void proto_gradido_gradido_deferred_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_deferred_transfer_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_deferred_transfer_t),
        (pbtools_message_encode_inner_t)proto_gradido_gradido_deferred_transfer_encode_inner);
}

void proto_gradido_gradido_deferred_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_deferred_transfer_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_deferred_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_deferred_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_deferred_transfer_decode_inner);
}

struct proto_gradido_gradido_deferred_transfer_t *
proto_gradido_gradido_deferred_transfer_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_gradido_deferred_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_deferred_transfer_init));
}

int proto_gradido_gradido_deferred_transfer_encode(
    struct proto_gradido_gradido_deferred_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_gradido_deferred_transfer_encode_inner));
}

int proto_gradido_gradido_deferred_transfer_decode(
    struct proto_gradido_gradido_deferred_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_deferred_transfer_decode_inner));
}

void proto_gradido_gradido_redeem_deferred_transfer_init(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->deferred_transfer_transaction_nr = 0;
    self_p->transfer_p = NULL;
}

void proto_gradido_gradido_redeem_deferred_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p)
{
    pbtools_encoder_sub_message_encode(
        encoder_p,
        2,
        (struct pbtools_message_base_t *)self_p->transfer_p,
        (pbtools_message_encode_inner_t)proto_gradido_gradido_transfer_encode_inner);
    pbtools_encoder_write_uint64(encoder_p, 1, self_p->deferred_transfer_transaction_nr);
}

void proto_gradido_gradido_redeem_deferred_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->deferred_transfer_transaction_nr = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        case 2:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->transfer_p,
                sizeof(struct proto_gradido_gradido_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_transfer_init,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_transfer_decode_inner);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int proto_gradido_gradido_redeem_deferred_transfer_transfer_alloc(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->transfer_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_transfer_init));
}

void proto_gradido_gradido_redeem_deferred_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_redeem_deferred_transfer_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_redeem_deferred_transfer_t),
        (pbtools_message_encode_inner_t)proto_gradido_gradido_redeem_deferred_transfer_encode_inner);
}

void proto_gradido_gradido_redeem_deferred_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_redeem_deferred_transfer_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_redeem_deferred_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_redeem_deferred_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_redeem_deferred_transfer_decode_inner);
}

struct proto_gradido_gradido_redeem_deferred_transfer_t *
proto_gradido_gradido_redeem_deferred_transfer_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_gradido_redeem_deferred_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_redeem_deferred_transfer_init));
}

int proto_gradido_gradido_redeem_deferred_transfer_encode(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_gradido_redeem_deferred_transfer_encode_inner));
}

int proto_gradido_gradido_redeem_deferred_transfer_decode(
    struct proto_gradido_gradido_redeem_deferred_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_redeem_deferred_transfer_decode_inner));
}

void proto_gradido_gradido_timeout_deferred_transfer_init(
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->deferred_transfer_transaction_nr = 0;
}

void proto_gradido_gradido_timeout_deferred_transfer_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p)
{
    pbtools_encoder_write_uint64(encoder_p, 1, self_p->deferred_transfer_transaction_nr);
}

void proto_gradido_gradido_timeout_deferred_transfer_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->deferred_transfer_transaction_nr = pbtools_decoder_read_uint64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_gradido_timeout_deferred_transfer_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_gradido_timeout_deferred_transfer_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_timeout_deferred_transfer_t),
        (pbtools_message_encode_inner_t)proto_gradido_gradido_timeout_deferred_transfer_encode_inner);
}

void proto_gradido_gradido_timeout_deferred_transfer_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_gradido_timeout_deferred_transfer_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_gradido_timeout_deferred_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_timeout_deferred_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_timeout_deferred_transfer_decode_inner);
}

struct proto_gradido_gradido_timeout_deferred_transfer_t *
proto_gradido_gradido_timeout_deferred_transfer_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_gradido_timeout_deferred_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_timeout_deferred_transfer_init));
}

int proto_gradido_gradido_timeout_deferred_transfer_encode(
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_gradido_timeout_deferred_transfer_encode_inner));
}

int proto_gradido_gradido_timeout_deferred_transfer_decode(
    struct proto_gradido_gradido_timeout_deferred_transfer_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_gradido_timeout_deferred_transfer_decode_inner));
}
