/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "hiero_basic_types.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void proto_gradido_account_id_account_num_init(
    struct proto_gradido_account_id_t *self_p)
{
    self_p->account = proto_gradido_account_id_account_account_num_e;
    self_p->account_num = 0;
}

void proto_gradido_account_id_alias_init(
    struct proto_gradido_account_id_t *self_p)
{
    self_p->account = proto_gradido_account_id_account_alias_e;
    pbtools_bytes_init(&self_p->alias);
}

static void proto_gradido_account_id_account_num_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_account_id_t *self_p)
{
    proto_gradido_account_id_account_num_init(self_p);
    self_p->account_num = pbtools_decoder_read_int64(
        decoder_p,
        wire_type);
}

static void proto_gradido_account_id_alias_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_account_id_t *self_p)
{
    proto_gradido_account_id_alias_init(self_p);
    pbtools_decoder_read_bytes(decoder_p,
                               wire_type,
                               &self_p->alias);
}

void proto_gradido_account_id_init(
    struct proto_gradido_account_id_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->shard_num = 0;
    self_p->realm_num = 0;
    self_p->account = 0;
}

void proto_gradido_account_id_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_account_id_t *self_p)
{
    pbtools_encoder_write_int64(encoder_p, 2, self_p->realm_num);
    pbtools_encoder_write_int64(encoder_p, 1, self_p->shard_num);
    switch (self_p->account) {

    case proto_gradido_account_id_account_account_num_e:
        pbtools_encoder_write_int64_always(
            encoder_p,
            3,
            self_p->account_num);
        break;

    case proto_gradido_account_id_account_alias_e:
        pbtools_encoder_write_bytes_always(
            encoder_p,
            4,
            &self_p->alias);
        break;

    default:
        break;
    }
}

void proto_gradido_account_id_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_account_id_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->shard_num = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 2:
            self_p->realm_num = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 3:
            proto_gradido_account_id_account_num_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 4:
            proto_gradido_account_id_alias_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_account_id_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_account_id_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_account_id_t),
        (pbtools_message_encode_inner_t)proto_gradido_account_id_encode_inner);
}

void proto_gradido_account_id_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_account_id_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_account_id_t),
        (pbtools_message_init_t)proto_gradido_account_id_init,
        (pbtools_message_decode_inner_t)proto_gradido_account_id_decode_inner);
}

struct proto_gradido_account_id_t *
proto_gradido_account_id_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_account_id_t),
                (pbtools_message_init_t)proto_gradido_account_id_init));
}

int proto_gradido_account_id_encode(
    struct proto_gradido_account_id_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_account_id_encode_inner));
}

int proto_gradido_account_id_decode(
    struct proto_gradido_account_id_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_account_id_decode_inner));
}

void proto_gradido_topic_id_init(
    struct proto_gradido_topic_id_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->shard_num = 0;
    self_p->realm_num = 0;
    self_p->topic_num = 0;
}

void proto_gradido_topic_id_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_topic_id_t *self_p)
{
    pbtools_encoder_write_int64(encoder_p, 3, self_p->topic_num);
    pbtools_encoder_write_int64(encoder_p, 2, self_p->realm_num);
    pbtools_encoder_write_int64(encoder_p, 1, self_p->shard_num);
}

void proto_gradido_topic_id_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_topic_id_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            self_p->shard_num = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 2:
            self_p->realm_num = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        case 3:
            self_p->topic_num = pbtools_decoder_read_int64(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_topic_id_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_topic_id_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_topic_id_t),
        (pbtools_message_encode_inner_t)proto_gradido_topic_id_encode_inner);
}

void proto_gradido_topic_id_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_topic_id_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_topic_id_t),
        (pbtools_message_init_t)proto_gradido_topic_id_init,
        (pbtools_message_decode_inner_t)proto_gradido_topic_id_decode_inner);
}

struct proto_gradido_topic_id_t *
proto_gradido_topic_id_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_topic_id_t),
                (pbtools_message_init_t)proto_gradido_topic_id_init));
}

int proto_gradido_topic_id_encode(
    struct proto_gradido_topic_id_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_topic_id_encode_inner));
}

int proto_gradido_topic_id_decode(
    struct proto_gradido_topic_id_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_topic_id_decode_inner));
}

void proto_gradido_transaction_id_init(
    struct proto_gradido_transaction_id_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->transaction_valid_start_p = NULL;
    self_p->account_id_p = NULL;
    self_p->scheduled = 0;
    self_p->nonce = 0;
}

void proto_gradido_transaction_id_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_transaction_id_t *self_p)
{
    pbtools_encoder_write_int32(encoder_p, 4, self_p->nonce);
    pbtools_encoder_write_bool(encoder_p, 3, self_p->scheduled);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        2,
        (struct pbtools_message_base_t *)self_p->account_id_p,
        (pbtools_message_encode_inner_t)proto_gradido_account_id_encode_inner);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        1,
        (struct pbtools_message_base_t *)self_p->transaction_valid_start_p,
        (pbtools_message_encode_inner_t)proto_gradido_timestamp_encode_inner);
}

void proto_gradido_transaction_id_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_transaction_id_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->transaction_valid_start_p,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init,
                (pbtools_message_decode_inner_t)proto_gradido_timestamp_decode_inner);
            break;

        case 2:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->account_id_p,
                sizeof(struct proto_gradido_account_id_t),
                (pbtools_message_init_t)proto_gradido_account_id_init,
                (pbtools_message_decode_inner_t)proto_gradido_account_id_decode_inner);
            break;

        case 3:
            self_p->scheduled = pbtools_decoder_read_bool(decoder_p, wire_type);
            break;

        case 4:
            self_p->nonce = pbtools_decoder_read_int32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

int proto_gradido_transaction_id_transaction_valid_start_alloc(
    struct proto_gradido_transaction_id_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->transaction_valid_start_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init));
}

int proto_gradido_transaction_id_account_id_alloc(
    struct proto_gradido_transaction_id_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->account_id_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_account_id_t),
                (pbtools_message_init_t)proto_gradido_account_id_init));
}

void proto_gradido_transaction_id_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_transaction_id_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_transaction_id_t),
        (pbtools_message_encode_inner_t)proto_gradido_transaction_id_encode_inner);
}

void proto_gradido_transaction_id_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_transaction_id_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_transaction_id_t),
        (pbtools_message_init_t)proto_gradido_transaction_id_init,
        (pbtools_message_decode_inner_t)proto_gradido_transaction_id_decode_inner);
}

struct proto_gradido_transaction_id_t *
proto_gradido_transaction_id_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_transaction_id_t),
                (pbtools_message_init_t)proto_gradido_transaction_id_init));
}

int proto_gradido_transaction_id_encode(
    struct proto_gradido_transaction_id_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_transaction_id_encode_inner));
}

int proto_gradido_transaction_id_decode(
    struct proto_gradido_transaction_id_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_transaction_id_decode_inner));
}
