/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "register_address.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

void proto_gradido_register_address_init(
    struct proto_gradido_register_address_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    pbtools_bytes_init(&self_p->user_pubkey);
    self_p->address_type = 0;
    pbtools_bytes_init(&self_p->name_hash);
    pbtools_bytes_init(&self_p->account_pubkey);
    self_p->derivation_index = 0;
}

void proto_gradido_register_address_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_register_address_t *self_p)
{
    pbtools_encoder_write_uint32(encoder_p, 5, self_p->derivation_index);
    pbtools_encoder_write_bytes(encoder_p, 4, &self_p->account_pubkey);
    pbtools_encoder_write_bytes(encoder_p, 3, &self_p->name_hash);
    pbtools_encoder_write_enum(encoder_p, 2, self_p->address_type);
    pbtools_encoder_write_bytes(encoder_p, 1, &self_p->user_pubkey);
}

void proto_gradido_register_address_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_register_address_t *self_p)
{
    int wire_type;

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->user_pubkey);
            break;

        case 2:
            self_p->address_type = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        case 3:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->name_hash);
            break;

        case 4:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->account_pubkey);
            break;

        case 5:
            self_p->derivation_index = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }
}

void proto_gradido_register_address_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_register_address_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_register_address_t),
        (pbtools_message_encode_inner_t)proto_gradido_register_address_encode_inner);
}

void proto_gradido_register_address_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_register_address_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_register_address_t),
        (pbtools_message_init_t)proto_gradido_register_address_init,
        (pbtools_message_decode_inner_t)proto_gradido_register_address_decode_inner);
}

struct proto_gradido_register_address_t *
proto_gradido_register_address_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_register_address_t),
                (pbtools_message_init_t)proto_gradido_register_address_init));
}

int proto_gradido_register_address_encode(
    struct proto_gradido_register_address_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_register_address_encode_inner));
}

int proto_gradido_register_address_decode(
    struct proto_gradido_register_address_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_register_address_decode_inner));
}
