/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by pbtools.
 */

#include <limits.h>
#include "transaction_body.h"

#if CHAR_BIT != 8
#    error "Number of bits in a char must be 8."
#endif

int proto_gradido_transaction_body_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_transfer_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->transfer_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_transfer_init));
}

int proto_gradido_transaction_body_creation_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_creation_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->creation_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_creation_t),
                (pbtools_message_init_t)proto_gradido_gradido_creation_init));
}

int proto_gradido_transaction_body_community_friends_update_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_community_friends_update_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->community_friends_update_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_community_friends_update_t),
                (pbtools_message_init_t)proto_gradido_community_friends_update_init));
}

int proto_gradido_transaction_body_register_address_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_register_address_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->register_address_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_register_address_t),
                (pbtools_message_init_t)proto_gradido_register_address_init));
}

int proto_gradido_transaction_body_deferred_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_deferred_transfer_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->deferred_transfer_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_deferred_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_deferred_transfer_init));
}

int proto_gradido_transaction_body_community_root_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_community_root_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->community_root_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_community_root_t),
                (pbtools_message_init_t)proto_gradido_community_root_init));
}

int proto_gradido_transaction_body_redeem_deferred_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_redeem_deferred_transfer_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->redeem_deferred_transfer_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_redeem_deferred_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_redeem_deferred_transfer_init));
}

int proto_gradido_transaction_body_timeout_deferred_transfer_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_timeout_deferred_transfer_e;

    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->timeout_deferred_transfer_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_gradido_timeout_deferred_transfer_t),
                (pbtools_message_init_t)proto_gradido_gradido_timeout_deferred_transfer_init));
}

static void proto_gradido_transaction_body_transfer_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_transfer_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->transfer_p,
        sizeof(struct proto_gradido_gradido_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_transfer_decode_inner);
}

static void proto_gradido_transaction_body_creation_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_creation_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->creation_p,
        sizeof(struct proto_gradido_gradido_creation_t),
        (pbtools_message_init_t)proto_gradido_gradido_creation_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_creation_decode_inner);
}

static void proto_gradido_transaction_body_community_friends_update_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_community_friends_update_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->community_friends_update_p,
        sizeof(struct proto_gradido_community_friends_update_t),
        (pbtools_message_init_t)proto_gradido_community_friends_update_init,
        (pbtools_message_decode_inner_t)proto_gradido_community_friends_update_decode_inner);
}

static void proto_gradido_transaction_body_register_address_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_register_address_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->register_address_p,
        sizeof(struct proto_gradido_register_address_t),
        (pbtools_message_init_t)proto_gradido_register_address_init,
        (pbtools_message_decode_inner_t)proto_gradido_register_address_decode_inner);
}

static void proto_gradido_transaction_body_deferred_transfer_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_deferred_transfer_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->deferred_transfer_p,
        sizeof(struct proto_gradido_gradido_deferred_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_deferred_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_deferred_transfer_decode_inner);
}

static void proto_gradido_transaction_body_community_root_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_community_root_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->community_root_p,
        sizeof(struct proto_gradido_community_root_t),
        (pbtools_message_init_t)proto_gradido_community_root_init,
        (pbtools_message_decode_inner_t)proto_gradido_community_root_decode_inner);
}

static void proto_gradido_transaction_body_redeem_deferred_transfer_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_redeem_deferred_transfer_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->redeem_deferred_transfer_p,
        sizeof(struct proto_gradido_gradido_redeem_deferred_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_redeem_deferred_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_redeem_deferred_transfer_decode_inner);
}

static void proto_gradido_transaction_body_timeout_deferred_transfer_decode(
    struct pbtools_decoder_t *decoder_p,
    int wire_type,
    struct proto_gradido_transaction_body_t *self_p)
{
    self_p->data = proto_gradido_transaction_body_data_timeout_deferred_transfer_e;
    pbtools_decoder_sub_message_decode(
        decoder_p,
        wire_type,
        (struct pbtools_message_base_t **)&self_p->timeout_deferred_transfer_p,
        sizeof(struct proto_gradido_gradido_timeout_deferred_transfer_t),
        (pbtools_message_init_t)proto_gradido_gradido_timeout_deferred_transfer_init,
        (pbtools_message_decode_inner_t)proto_gradido_gradido_timeout_deferred_transfer_decode_inner);
}

void proto_gradido_transaction_body_init(
    struct proto_gradido_transaction_body_t *self_p,
    struct pbtools_heap_t *heap_p)
{
    self_p->base.heap_p = heap_p;
    self_p->memos.length = 0;
    self_p->created_at_p = NULL;
    self_p->version_number = 0;
    self_p->type = 0;
    pbtools_bytes_init(&self_p->other_community_uuid);
    self_p->data = 0;
}

void proto_gradido_transaction_body_encode_inner(
    struct pbtools_encoder_t *encoder_p,
    struct proto_gradido_transaction_body_t *self_p)
{
    pbtools_encoder_write_bytes(encoder_p, 5, &self_p->other_community_uuid);
    pbtools_encoder_write_enum(encoder_p, 4, self_p->type);
    pbtools_encoder_write_uint32(encoder_p, 3, self_p->version_number);
    pbtools_encoder_sub_message_encode(
        encoder_p,
        2,
        (struct pbtools_message_base_t *)self_p->created_at_p,
        (pbtools_message_encode_inner_t)proto_gradido_timestamp_encode_inner);
    proto_gradido_encrypted_memo_encode_repeated_inner(
        encoder_p,
        1,
        &self_p->memos);
    switch (self_p->data) {

    case proto_gradido_transaction_body_data_transfer_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            6,
            &self_p->transfer_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_gradido_transfer_encode_inner);
        break;

    case proto_gradido_transaction_body_data_creation_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            7,
            &self_p->creation_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_gradido_creation_encode_inner);
        break;

    case proto_gradido_transaction_body_data_community_friends_update_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            8,
            &self_p->community_friends_update_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_community_friends_update_encode_inner);
        break;

    case proto_gradido_transaction_body_data_register_address_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            9,
            &self_p->register_address_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_register_address_encode_inner);
        break;

    case proto_gradido_transaction_body_data_deferred_transfer_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            10,
            &self_p->deferred_transfer_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_gradido_deferred_transfer_encode_inner);
        break;

    case proto_gradido_transaction_body_data_community_root_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            11,
            &self_p->community_root_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_community_root_encode_inner);
        break;

    case proto_gradido_transaction_body_data_redeem_deferred_transfer_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            12,
            &self_p->redeem_deferred_transfer_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_gradido_redeem_deferred_transfer_encode_inner);
        break;

    case proto_gradido_transaction_body_data_timeout_deferred_transfer_e:
        pbtools_encoder_sub_message_encode_always(
            encoder_p,
            13,
            &self_p->timeout_deferred_transfer_p->base,
            (pbtools_message_encode_inner_t)proto_gradido_gradido_timeout_deferred_transfer_encode_inner);
        break;

    default:
        break;
    }
}

void proto_gradido_transaction_body_decode_inner(
    struct pbtools_decoder_t *decoder_p,
    struct proto_gradido_transaction_body_t *self_p)
{
    int wire_type;
    struct pbtools_repeated_info_t repeated_info_memos;

    pbtools_repeated_info_init(&repeated_info_memos, 1);

    while (pbtools_decoder_available(decoder_p)) {
        switch (pbtools_decoder_read_tag(decoder_p, &wire_type)) {

        case 1:
            pbtools_repeated_info_decode(&repeated_info_memos,
                                         decoder_p,
                                         wire_type);
            break;

        case 2:
            pbtools_decoder_sub_message_decode(
                decoder_p,
                wire_type,
                (struct pbtools_message_base_t **)&self_p->created_at_p,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init,
                (pbtools_message_decode_inner_t)proto_gradido_timestamp_decode_inner);
            break;

        case 3:
            self_p->version_number = pbtools_decoder_read_uint32(decoder_p, wire_type);
            break;

        case 4:
            self_p->type = pbtools_decoder_read_enum(decoder_p, wire_type);
            break;

        case 5:
            pbtools_decoder_read_bytes(decoder_p, wire_type, &self_p->other_community_uuid);
            break;

        case 6:
            proto_gradido_transaction_body_transfer_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 7:
            proto_gradido_transaction_body_creation_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 8:
            proto_gradido_transaction_body_community_friends_update_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 9:
            proto_gradido_transaction_body_register_address_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 10:
            proto_gradido_transaction_body_deferred_transfer_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 11:
            proto_gradido_transaction_body_community_root_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 12:
            proto_gradido_transaction_body_redeem_deferred_transfer_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        case 13:
            proto_gradido_transaction_body_timeout_deferred_transfer_decode(
                decoder_p,
                wire_type,
                self_p);
            break;

        default:
            pbtools_decoder_skip_field(decoder_p, wire_type);
            break;
        }
    }

    proto_gradido_encrypted_memo_decode_repeated_inner(
        decoder_p,
        &repeated_info_memos,
        &self_p->memos);
}

int proto_gradido_transaction_body_created_at_alloc(
    struct proto_gradido_transaction_body_t *self_p)
{
    return (pbtools_sub_message_alloc(
                (struct pbtools_message_base_t **)&self_p->created_at_p,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_timestamp_t),
                (pbtools_message_init_t)proto_gradido_timestamp_init));
}

int proto_gradido_transaction_body_memos_alloc(
    struct proto_gradido_transaction_body_t *self_p,
    int length)
{
    return (pbtools_alloc_repeated(
                (struct pbtools_repeated_message_t *)&self_p->memos,
                length,
                self_p->base.heap_p,
                sizeof(struct proto_gradido_encrypted_memo_t),
                (pbtools_message_init_t)proto_gradido_encrypted_memo_init));
}

void proto_gradido_transaction_body_encode_repeated_inner(
    struct pbtools_encoder_t *encoder_p,
    int field_number,
    struct proto_gradido_transaction_body_repeated_t *repeated_p)
{
    pbtools_encode_repeated_inner(
        encoder_p,
        field_number,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_transaction_body_t),
        (pbtools_message_encode_inner_t)proto_gradido_transaction_body_encode_inner);
}

void proto_gradido_transaction_body_decode_repeated_inner(
    struct pbtools_decoder_t *decoder_p,
    struct pbtools_repeated_info_t *repeated_info_p,
    struct proto_gradido_transaction_body_repeated_t *repeated_p)
{
    pbtools_decode_repeated_inner(
        decoder_p,
        repeated_info_p,
        (struct pbtools_repeated_message_t *)repeated_p,
        sizeof(struct proto_gradido_transaction_body_t),
        (pbtools_message_init_t)proto_gradido_transaction_body_init,
        (pbtools_message_decode_inner_t)proto_gradido_transaction_body_decode_inner);
}

struct proto_gradido_transaction_body_t *
proto_gradido_transaction_body_new(
    void *workspace_p,
    size_t size)
{
    return (pbtools_message_new(
                workspace_p,
                size,
                sizeof(struct proto_gradido_transaction_body_t),
                (pbtools_message_init_t)proto_gradido_transaction_body_init));
}

int proto_gradido_transaction_body_encode(
    struct proto_gradido_transaction_body_t *self_p,
    uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_encode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_encode_inner_t)proto_gradido_transaction_body_encode_inner));
}

int proto_gradido_transaction_body_decode(
    struct proto_gradido_transaction_body_t *self_p,
    const uint8_t *encoded_p,
    size_t size)
{
    return (pbtools_message_decode(
                &self_p->base,
                encoded_p,
                size,
                (pbtools_message_decode_inner_t)proto_gradido_transaction_body_decode_inner));
}
