<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateGroupChangeParent.proto

namespace GPBMetadata;

class StateGroupChangeParent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a020a1c537461746547726f75704368616e6765506172656e742e7072" .
            "6f746f12166d6f64656c2e6d657373616765732e6772616469646f22c901" .
            "0a16537461746547726f75704368616e6765506172656e7412330a0e6772" .
            "6f75705075626c69634b657918012001280b321b2e6d6f64656c2e6d6573" .
            "73616765732e6772616469646f2e4b6579123c0a176e6577506172656e74" .
            "47726f75705075626c69634b657918022001280b321b2e6d6f64656c2e6d" .
            "657373616765732e6772616469646f2e4b6579123c0a176f6c6450617265" .
            "6e7447726f75705075626c69634b657918032001280b321b2e6d6f64656c" .
            "2e6d657373616765732e6772616469646f2e4b6579620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

