<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateCreateGroup.proto

namespace GPBMetadata;

class StateCreateGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4010a16537461746543726561746547726f75702e70726f746f12166d" .
            "6f64656c2e6d657373616765732e6772616469646f22a9010a1053746174" .
            "6543726561746547726f7570120c0a046e616d6518012001280912330a0e" .
            "67726f75705075626c69634b657918022001280b321b2e6d6f64656c2e6d" .
            "657373616765732e6772616469646f2e4b657912390a14706172656e7447" .
            "726f75705075626c69634b657918032001280b321b2e6d6f64656c2e6d65" .
            "7373616765732e6772616469646f2e4b65794a0408041005521168656465" .
            "7261436f6e73656e7375734964620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

