<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transaction.proto

namespace GPBMetadata;

class Transaction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4010a115472616e73616374696f6e2e70726f746f12166d6f64656c2e" .
            "6d657373616765732e6772616469646f22ae010a0b5472616e7361637469" .
            "6f6e120a0a026964180120012804123a0a08726563656976656418022001" .
            "280b32282e6d6f64656c2e6d657373616765732e6772616469646f2e5469" .
            "6d657374616d705365636f6e647312340a067369674d617018032001280b" .
            "32242e6d6f64656c2e6d657373616765732e6772616469646f2e5369676e" .
            "61747572654d6170120e0a0674784861736818042001280c12110a09626f" .
            "6479427974657318052001280c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

