<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionCreation.proto

namespace GPBMetadata;

class TransactionCreation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88010a195472616e73616374696f6e4372656174696f6e2e70726f746f" .
            "12076772616469646f225a0a135472616e73616374696f6e437265617469" .
            "6f6e122f0a0e7265636569766572416d6f756e7418012001280b32172e67" .
            "72616469646f2e5265636569766572416d6f756e7412120a0a6964656e74" .
            "5f68617368180220012811620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

