<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateCreateGroup.proto

namespace GPBMetadata;

class StateCreateGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7010a16537461746543726561746547726f75702e70726f746f120767" .
            "72616469646f228b010a10537461746543726561746547726f7570120c0a" .
            "046e616d6518012001280912240a0e67726f75705075626c69634b657918" .
            "022001280b320c2e6772616469646f2e4b6579122a0a14706172656e7447" .
            "726f75705075626c69634b657918032001280b320c2e6772616469646f2e" .
            "4b65794a04080410055211686564657261436f6e73656e73757349646206" .
            "70726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

