<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateGroupChangeParent.proto

namespace GPBMetadata;

class StateGroupChangeParent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace010a1c537461746547726f75704368616e6765506172656e742e7072" .
            "6f746f12076772616469646f229c010a16537461746547726f7570436861" .
            "6e6765506172656e7412240a0e67726f75705075626c69634b6579180120" .
            "01280b320c2e6772616469646f2e4b6579122d0a176e6577506172656e74" .
            "47726f75705075626c69634b657918022001280b320c2e6772616469646f" .
            "2e4b6579122d0a176f6c64506172656e7447726f75705075626c69634b65" .
            "7918032001280b320c2e6772616469646f2e4b6579620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

