<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transfer.proto

namespace GPBMetadata;

class Transfer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d010a0e5472616e736665722e70726f746f12076772616469646f226a" .
            "0a085472616e73666572122c0a0d73656e646572416d6f756e7473180120" .
            "03280b32152e6772616469646f2e53656e646572416d6f756e7412300a0f" .
            "7265636569766572416d6f756e747318022003280b32172e677261646964" .
            "6f2e5265636569766572416d6f756e74620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

