<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GlobalGroupAdd.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.GlobalGroupAdd</code>
 */
class GlobalGroupAdd extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string group_name = 1;</code>
     */
    protected $group_name = '';
    /**
     * Generated from protobuf field <code>string group_alias = 2;</code>
     */
    protected $group_alias = '';
    /**
     * Generated from protobuf field <code>string parent_group_alias = 3;</code>
     */
    protected $parent_group_alias = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $group_name
     *     @type string $group_alias
     *     @type string $parent_group_alias
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GlobalGroupAdd::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string group_name = 1;</code>
     * @return string
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * Generated from protobuf field <code>string group_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_alias = 2;</code>
     * @return string
     */
    public function getGroupAlias()
    {
        return $this->group_alias;
    }

    /**
     * Generated from protobuf field <code>string group_alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_alias = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_group_alias = 3;</code>
     * @return string
     */
    public function getParentGroupAlias()
    {
        return $this->parent_group_alias;
    }

    /**
     * Generated from protobuf field <code>string parent_group_alias = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParentGroupAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_group_alias = $var;

        return $this;
    }

}

