<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoTransfer.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.GradidoTransfer</code>
 */
class GradidoTransfer extends \Google\Protobuf\Internal\Message
{
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Gradido\LocalTransfer $local
     *     @type \Proto\Gradido\CrossGroupTransfer $inbound
     *     @type \Proto\Gradido\CrossGroupTransfer $outbound
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GradidoTransfer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.LocalTransfer local = 1;</code>
     * @return \Proto\Gradido\LocalTransfer|null
     */
    public function getLocal()
    {
        return $this->readOneof(1);
    }

    public function hasLocal()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.LocalTransfer local = 1;</code>
     * @param \Proto\Gradido\LocalTransfer $var
     * @return $this
     */
    public function setLocal($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\LocalTransfer::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.CrossGroupTransfer inbound = 2;</code>
     * @return \Proto\Gradido\CrossGroupTransfer|null
     */
    public function getInbound()
    {
        return $this->readOneof(2);
    }

    public function hasInbound()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.CrossGroupTransfer inbound = 2;</code>
     * @param \Proto\Gradido\CrossGroupTransfer $var
     * @return $this
     */
    public function setInbound($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\CrossGroupTransfer::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.CrossGroupTransfer outbound = 3;</code>
     * @return \Proto\Gradido\CrossGroupTransfer|null
     */
    public function getOutbound()
    {
        return $this->readOneof(3);
    }

    public function hasOutbound()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.CrossGroupTransfer outbound = 3;</code>
     * @param \Proto\Gradido\CrossGroupTransfer $var
     * @return $this
     */
    public function setOutbound($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\CrossGroupTransfer::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

