<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoCreation.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * need signature from group admin or 
 * percent of group users another than the receiver
 *
 * Generated from protobuf message <code>proto.gradido.GradidoCreation</code>
 */
class GradidoCreation extends \Google\Protobuf\Internal\Message
{
    /**
     * 40 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TransferAmount recipiant = 1;</code>
     */
    protected $recipiant = null;
    /**
     * 8 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds target_date = 3;</code>
     */
    protected $target_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Gradido\TransferAmount $recipiant
     *           40 Byte
     *     @type \Proto\Gradido\TimestampSeconds $target_date
     *           8 Byte
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GradidoCreation::initOnce();
        parent::__construct($data);
    }

    /**
     * 40 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TransferAmount recipiant = 1;</code>
     * @return \Proto\Gradido\TransferAmount|null
     */
    public function getRecipiant()
    {
        return isset($this->recipiant) ? $this->recipiant : null;
    }

    public function hasRecipiant()
    {
        return isset($this->recipiant);
    }

    public function clearRecipiant()
    {
        unset($this->recipiant);
    }

    /**
     * 40 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TransferAmount recipiant = 1;</code>
     * @param \Proto\Gradido\TransferAmount $var
     * @return $this
     */
    public function setRecipiant($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\TransferAmount::class);
        $this->recipiant = $var;

        return $this;
    }

    /**
     * 8 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds target_date = 3;</code>
     * @return \Proto\Gradido\TimestampSeconds|null
     */
    public function getTargetDate()
    {
        return isset($this->target_date) ? $this->target_date : null;
    }

    public function hasTargetDate()
    {
        return isset($this->target_date);
    }

    public function clearTargetDate()
    {
        unset($this->target_date);
    }

    /**
     * 8 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds target_date = 3;</code>
     * @param \Proto\Gradido\TimestampSeconds $var
     * @return $this
     */
    public function setTargetDate($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\TimestampSeconds::class);
        $this->target_date = $var;

        return $this;
    }

}

