<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoBlock.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.GradidoBlock</code>
 */
class GradidoBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoTransaction transaction = 2;</code>
     */
    protected $transaction = null;
    /**
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds received = 3;</code>
     */
    protected $received = null;
    /**
     * Generated from protobuf field <code>uint32 version_number = 4;</code>
     */
    protected $version_number = 0;
    /**
     * Generated from protobuf field <code>bytes running_hash = 5;</code>
     */
    protected $running_hash = '';
    /**
     * message id in underlaying blockchain like iota
     *
     * Generated from protobuf field <code>bytes message_id = 6;</code>
     */
    protected $message_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type \Proto\Gradido\GradidoTransaction $transaction
     *     @type \Proto\Gradido\TimestampSeconds $received
     *     @type int $version_number
     *     @type string $running_hash
     *     @type string $message_id
     *           message id in underlaying blockchain like iota
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GradidoBlock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoTransaction transaction = 2;</code>
     * @return \Proto\Gradido\GradidoTransaction|null
     */
    public function getTransaction()
    {
        return isset($this->transaction) ? $this->transaction : null;
    }

    public function hasTransaction()
    {
        return isset($this->transaction);
    }

    public function clearTransaction()
    {
        unset($this->transaction);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GradidoTransaction transaction = 2;</code>
     * @param \Proto\Gradido\GradidoTransaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\GradidoTransaction::class);
        $this->transaction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds received = 3;</code>
     * @return \Proto\Gradido\TimestampSeconds|null
     */
    public function getReceived()
    {
        return isset($this->received) ? $this->received : null;
    }

    public function hasReceived()
    {
        return isset($this->received);
    }

    public function clearReceived()
    {
        unset($this->received);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds received = 3;</code>
     * @param \Proto\Gradido\TimestampSeconds $var
     * @return $this
     */
    public function setReceived($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\TimestampSeconds::class);
        $this->received = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 4;</code>
     * @return int
     */
    public function getVersionNumber()
    {
        return $this->version_number;
    }

    /**
     * Generated from protobuf field <code>uint32 version_number = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVersionNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->version_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes running_hash = 5;</code>
     * @return string
     */
    public function getRunningHash()
    {
        return $this->running_hash;
    }

    /**
     * Generated from protobuf field <code>bytes running_hash = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRunningHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->running_hash = $var;

        return $this;
    }

    /**
     * message id in underlaying blockchain like iota
     *
     * Generated from protobuf field <code>bytes message_id = 6;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * message id in underlaying blockchain like iota
     *
     * Generated from protobuf field <code>bytes message_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, False);
        $this->message_id = $var;

        return $this;
    }

}

