<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoCreation.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * need signature from group admin or 
 * percent of group users another than the receiver
 *
 * Generated from protobuf message <code>proto.gradido.GradidoCreation</code>
 */
class GradidoCreation extends \Google\Protobuf\Internal\Message
{
    /**
     * 40 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TransferAmount receiver = 1;</code>
     */
    private $receiver = null;
    /**
     * 8 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds target_date = 3;</code>
     */
    private $target_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Gradido\TransferAmount $receiver
     *           40 Byte
     *     @type \Proto\Gradido\TimestampSeconds $target_date
     *           8 Byte
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GradidoCreation::initOnce();
        parent::__construct($data);
    }

    /**
     * 40 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TransferAmount receiver = 1;</code>
     * @return \Proto\Gradido\TransferAmount
     */
    public function getReceiver()
    {
        return $this->receiver;
    }

    /**
     * 40 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TransferAmount receiver = 1;</code>
     * @param \Proto\Gradido\TransferAmount $var
     * @return $this
     */
    public function setReceiver($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\TransferAmount::class);
        $this->receiver = $var;

        return $this;
    }

    /**
     * 8 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds target_date = 3;</code>
     * @return \Proto\Gradido\TimestampSeconds
     */
    public function getTargetDate()
    {
        return $this->target_date;
    }

    /**
     * 8 Byte
     *
     * Generated from protobuf field <code>.proto.gradido.TimestampSeconds target_date = 3;</code>
     * @param \Proto\Gradido\TimestampSeconds $var
     * @return $this
     */
    public function setTargetDate($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\TimestampSeconds::class);
        $this->target_date = $var;

        return $this;
    }

}

