<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GroupFriendsUpdate.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.GroupFriendsUpdate</code>
 */
class GroupFriendsUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * char[16], alias
     *
     * Generated from protobuf field <code>string group = 1;</code>
     */
    protected $group = '';
    /**
     * Generated from protobuf field <code>.proto.gradido.GroupFriendsUpdate.Action action = 2;</code>
     */
    protected $action = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $group
     *           char[16], alias
     *     @type int $action
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GroupFriendsUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * char[16], alias
     *
     * Generated from protobuf field <code>string group = 1;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * char[16], alias
     *
     * Generated from protobuf field <code>string group = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GroupFriendsUpdate.Action action = 2;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.GroupFriendsUpdate.Action action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Proto\Gradido\GroupFriendsUpdate\Action::class);
        $this->action = $var;

        return $this;
    }

}

