<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/BasicTypes.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.Key</code>
 */
class Key extends \Google\Protobuf\Internal\Message
{
    /**
     * ed25519 signature (libsodium default)
     *
     * Generated from protobuf field <code>bytes ed25519 = 2;</code>
     */
    protected $ed25519 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ed25519
     *           ed25519 signature (libsodium default)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * ed25519 signature (libsodium default)
     *
     * Generated from protobuf field <code>bytes ed25519 = 2;</code>
     * @return string
     */
    public function getEd25519()
    {
        return $this->ed25519;
    }

    /**
     * ed25519 signature (libsodium default)
     *
     * Generated from protobuf field <code>bytes ed25519 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEd25519($var)
    {
        GPBUtil::checkString($var, False);
        $this->ed25519 = $var;

        return $this;
    }

}

