<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GradidoTransfer.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.LocalTransfer</code>
 */
class LocalTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.gradido.TransferAmount sender = 1;</code>
     */
    private $sender = null;
    /**
     * Generated from protobuf field <code>bytes receiver = 2;</code>
     */
    private $receiver = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Gradido\TransferAmount $sender
     *     @type string $receiver
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\GradidoTransfer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.TransferAmount sender = 1;</code>
     * @return \Proto\Gradido\TransferAmount
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.TransferAmount sender = 1;</code>
     * @param \Proto\Gradido\TransferAmount $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\TransferAmount::class);
        $this->sender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes receiver = 2;</code>
     * @return string
     */
    public function getReceiver()
    {
        return $this->receiver;
    }

    /**
     * Generated from protobuf field <code>bytes receiver = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiver($var)
    {
        GPBUtil::checkString($var, False);
        $this->receiver = $var;

        return $this;
    }

}

