<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/ManageNodeRequest.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.ManageNodeRequest</code>
 */
class ManageNodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.gradido.SignatureMap sig_map = 1;</code>
     */
    protected $sig_map = null;
    /**
     * ManageNodeBody
     *
     * Generated from protobuf field <code>bytes body_bytes = 2;</code>
     */
    protected $body_bytes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Gradido\SignatureMap $sig_map
     *     @type string $body_bytes
     *           ManageNodeBody
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\ManageNodeRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.SignatureMap sig_map = 1;</code>
     * @return \Proto\Gradido\SignatureMap|null
     */
    public function getSigMap()
    {
        return isset($this->sig_map) ? $this->sig_map : null;
    }

    public function hasSigMap()
    {
        return isset($this->sig_map);
    }

    public function clearSigMap()
    {
        unset($this->sig_map);
    }

    /**
     * Generated from protobuf field <code>.proto.gradido.SignatureMap sig_map = 1;</code>
     * @param \Proto\Gradido\SignatureMap $var
     * @return $this
     */
    public function setSigMap($var)
    {
        GPBUtil::checkMessage($var, \Proto\Gradido\SignatureMap::class);
        $this->sig_map = $var;

        return $this;
    }

    /**
     * ManageNodeBody
     *
     * Generated from protobuf field <code>bytes body_bytes = 2;</code>
     * @return string
     */
    public function getBodyBytes()
    {
        return $this->body_bytes;
    }

    /**
     * ManageNodeBody
     *
     * Generated from protobuf field <code>bytes body_bytes = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBodyBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->body_bytes = $var;

        return $this;
    }

}

