<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/ManageNodeRequest.proto

namespace Proto\Gradido;

if (false) {
    /**
     * This class is deprecated. Use Proto\Gradido\ManageNodeResponse\ErrorCode instead.
     * @deprecated
     */
    class ManageNodeResponse_ErrorCode {}
}
class_exists(ManageNodeResponse\ErrorCode::class);
@trigger_error('Proto\Gradido\ManageNodeResponse_ErrorCode is deprecated and will be removed in the next major release. Use Proto\Gradido\ManageNodeResponse\ErrorCode instead', E_USER_DEPRECATED);

