<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/BasicTypes.proto

namespace Proto\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.gradido.TransferAmount</code>
 */
class TransferAmount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes pubkey = 1;</code>
     */
    protected $pubkey = '';
    /**
     * Generated from protobuf field <code>sint64 amount = 2;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pubkey
     *     @type int|string $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gradido\BasicTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes pubkey = 1;</code>
     * @return string
     */
    public function getPubkey()
    {
        return $this->pubkey;
    }

    /**
     * Generated from protobuf field <code>bytes pubkey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>sint64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

