#ifndef GRADIDO_BLOCKCHAIN_CORE_CONST_H
#define GRADIDO_BLOCKCHAIN_CORE_CONST_H

#ifdef __cplusplus
extern "C" {
#endif

#define ED25519_PUBLIC_KEY_SIZE 32
#define ED25519_SEED_SIZE 32
#define ED25519_CHAIN_CODE_SIZE 32
#define ED25519_PRIVATE_KEY_SIZE 64
#define ED25519_SIGNATURE_SIZE 64
#define BLAKE2B_HASH_SIZE 32
#define UUID_BINARY_SIZE 16
const static int MAGIC_NUMBER_MAX_TIMESPAN_BETWEEN_CREATING_AND_RECEIVING_TRANSACTION_SECONDS = 120;

#ifdef __cplusplus
}
#endif

#endif // GRADIDO_BLOCKCHAIN_CORE_CONST_H
