<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gradido/GroupFriendsUpdate.proto

namespace Proto\Gradido\GroupFriendsUpdate;

use UnexpectedValueException;

/**
 * Protobuf type <code>proto.gradido.GroupFriendsUpdate.Action</code>
 */
class Action
{
    /**
     * Generated from protobuf enum <code>ADD_FRIEND = 0;</code>
     */
    const ADD_FRIEND = 0;
    /**
     * Generated from protobuf enum <code>REMOVE_FRIEND = 1;</code>
     */
    const REMOVE_FRIEND = 1;

    private static $valueToName = [
        self::ADD_FRIEND => 'ADD_FRIEND',
        self::REMOVE_FRIEND => 'REMOVE_FRIEND',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Action::class, \Proto\Gradido\GroupFriendsUpdate_Action::class);

