/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeUserRoleFormular: typeof import('./src/components/ChangeUserRoleFormular.vue')['default']
    CommunityVisualizeItem: typeof import('./src/components/Federation/CommunityVisualizeItem.vue')['default']
    ConfirmRegisterMailFormular: typeof import('./src/components/ConfirmRegisterMailFormular.vue')['default']
    ContentFooter: typeof import('./src/components/ContentFooter.vue')['default']
    ContributionLink: typeof import('./src/components/ContributionLink/ContributionLink.vue')['default']
    ContributionLinkForm: typeof import('./src/components/ContributionLink/ContributionLinkForm.vue')['default']
    ContributionLinkList: typeof import('./src/components/ContributionLink/ContributionLinkList.vue')['default']
    ContributionMessagesFormular: typeof import('./src/components/ContributionMessages/ContributionMessagesFormular.vue')['default']
    ContributionMessagesList: typeof import('./src/components/ContributionMessages/ContributionMessagesList.vue')['default']
    ContributionMessagesListItem: typeof import('./src/components/ContributionMessages/slots/ContributionMessagesListItem.vue')['default']
    Coordinates: typeof import('./src/components/input/Coordinates.vue')['default']
    CreationFormular: typeof import('./src/components/CreationFormular.vue')['default']
    CreationTransactionList: typeof import('./src/components/CreationTransactionList.vue')['default']
    DeletedUserFormular: typeof import('./src/components/DeletedUserFormular.vue')['default']
    EditableGroup: typeof import('./src/components/input/EditableGroup.vue')['default']
    EditableGroupableLabel: typeof import('./src/components/input/EditableGroupableLabel.vue')['default']
    EditCreationFormular: typeof import('./src/components/EditCreationFormular.vue')['default']
    FederationVisualizeItem: typeof import('./src/components/Federation/FederationVisualizeItem.vue')['default']
    FigureQrCode: typeof import('./src/components/FigureQrCode.vue')['default']
    IBiEnvelope: typeof import('~icons/bi/envelope')['default']
    IBiXCircle: typeof import('~icons/bi/x-circle')['default']
    IIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IOcticonCircleSlash24: typeof import('~icons/octicon/circle-slash24')['default']
    IOcticonPerson24: typeof import('~icons/octicon/person24')['default']
    IPhCaretDown: typeof import('~icons/ph/caret-down')['default']
    IPhCaretUpFill: typeof import('~icons/ph/caret-up-fill')['default']
    IPhEnvelope: typeof import('~icons/ph/envelope')['default']
    IPhXCircle: typeof import('~icons/ph/x-circle')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NotFoundPage: typeof import('./src/components/NotFoundPage.vue')['default']
    OpenCreationsTable: typeof import('./src/components/Tables/OpenCreationsTable.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    ParseMessage: typeof import('./src/components/ContributionMessages/ParseMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowDetails: typeof import('./src/components/RowDetails.vue')['default']
    SearchUserTable: typeof import('./src/components/Tables/SearchUserTable.vue')['default']
    StatisticTable: typeof import('./src/components/Tables/StatisticTable.vue')['default']
    TimePicker: typeof import('./src/components/input/TimePicker.vue')['default']
    TransactionLinkList: typeof import('./src/components/TransactionLinkList.vue')['default']
    UserQuery: typeof import('./src/components/UserQuery.vue')['default']
  }
}
