<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transfer.proto

namespace GPBMetadata;

class Transfer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a0e5472616e736665722e70726f746f12166d6f64656c2e6d6573" .
            "73616765732e6772616469646f2288010a085472616e73666572123b0a0d" .
            "73656e646572416d6f756e747318012003280b32242e6d6f64656c2e6d65" .
            "7373616765732e6772616469646f2e53656e646572416d6f756e74123f0a" .
            "0f7265636569766572416d6f756e747318022003280b32262e6d6f64656c" .
            "2e6d657373616765732e6772616469646f2e5265636569766572416d6f75" .
            "6e74620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

