<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionCreation.proto

namespace GPBMetadata;

class TransactionCreation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BasicTypes::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6010a195472616e73616374696f6e4372656174696f6e2e70726f746f" .
            "12166d6f64656c2e6d657373616765732e6772616469646f22a8010a1354" .
            "72616e73616374696f6e4372656174696f6e123e0a0e7265636569766572" .
            "416d6f756e7418012001280b32262e6d6f64656c2e6d657373616765732e" .
            "6772616469646f2e5265636569766572416d6f756e7412120a0a6964656e" .
            "745f68617368180220012811123d0a0b7461726765745f64617465180320" .
            "01280b32282e6d6f64656c2e6d657373616765732e6772616469646f2e54" .
            "696d657374616d705365636f6e6473620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

