<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateGroupChangeParent.proto

namespace Model\Messages\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * need signature from this group and from both parents (if it isn't zero)
 *
 * Generated from protobuf message <code>model.messages.gradido.StateGroupChangeParent</code>
 */
class StateGroupChangeParent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key groupPublicKey = 1;</code>
     */
    private $groupPublicKey = null;
    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key newParentGroupPublicKey = 2;</code>
     */
    private $newParentGroupPublicKey = null;
    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key oldParentGroupPublicKey = 3;</code>
     */
    private $oldParentGroupPublicKey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Model\Messages\Gradido\Key $groupPublicKey
     *     @type \Model\Messages\Gradido\Key $newParentGroupPublicKey
     *     @type \Model\Messages\Gradido\Key $oldParentGroupPublicKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StateGroupChangeParent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key groupPublicKey = 1;</code>
     * @return \Model\Messages\Gradido\Key
     */
    public function getGroupPublicKey()
    {
        return $this->groupPublicKey;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key groupPublicKey = 1;</code>
     * @param \Model\Messages\Gradido\Key $var
     * @return $this
     */
    public function setGroupPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\Key::class);
        $this->groupPublicKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key newParentGroupPublicKey = 2;</code>
     * @return \Model\Messages\Gradido\Key
     */
    public function getNewParentGroupPublicKey()
    {
        return $this->newParentGroupPublicKey;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key newParentGroupPublicKey = 2;</code>
     * @param \Model\Messages\Gradido\Key $var
     * @return $this
     */
    public function setNewParentGroupPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\Key::class);
        $this->newParentGroupPublicKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key oldParentGroupPublicKey = 3;</code>
     * @return \Model\Messages\Gradido\Key
     */
    public function getOldParentGroupPublicKey()
    {
        return $this->oldParentGroupPublicKey;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key oldParentGroupPublicKey = 3;</code>
     * @param \Model\Messages\Gradido\Key $var
     * @return $this
     */
    public function setOldParentGroupPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\Key::class);
        $this->oldParentGroupPublicKey = $var;

        return $this;
    }

}

