<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateCreateGroup.proto

namespace Model\Messages\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * need signature from this group and from parent (if it isn't zero)
 *
 * Generated from protobuf message <code>model.messages.gradido.StateCreateGroup</code>
 */
class StateCreateGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key groupPublicKey = 2;</code>
     */
    private $groupPublicKey = null;
    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key parentGroupPublicKey = 3;</code>
     */
    private $parentGroupPublicKey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Model\Messages\Gradido\Key $groupPublicKey
     *     @type \Model\Messages\Gradido\Key $parentGroupPublicKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StateCreateGroup::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key groupPublicKey = 2;</code>
     * @return \Model\Messages\Gradido\Key
     */
    public function getGroupPublicKey()
    {
        return $this->groupPublicKey;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key groupPublicKey = 2;</code>
     * @param \Model\Messages\Gradido\Key $var
     * @return $this
     */
    public function setGroupPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\Key::class);
        $this->groupPublicKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key parentGroupPublicKey = 3;</code>
     * @return \Model\Messages\Gradido\Key
     */
    public function getParentGroupPublicKey()
    {
        return $this->parentGroupPublicKey;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Key parentGroupPublicKey = 3;</code>
     * @param \Model\Messages\Gradido\Key $var
     * @return $this
     */
    public function setParentGroupPublicKey($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\Key::class);
        $this->parentGroupPublicKey = $var;

        return $this;
    }

}

