<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionBody.proto

namespace Model\Messages\Gradido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.messages.gradido.TransactionBody</code>
 */
class TransactionBody extends \Google\Protobuf\Internal\Message
{
    /**
     * max 150 chars
     *
     * Generated from protobuf field <code>string memo = 1;</code>
     */
    private $memo = '';
    /**
     * Generated from protobuf field <code>.model.messages.gradido.TimestampSeconds created = 2;</code>
     */
    private $created = null;
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $memo
     *           max 150 chars
     *     @type \Model\Messages\Gradido\TimestampSeconds $created
     *     @type \Model\Messages\Gradido\StateCreateGroup $createGroup
     *     @type \Model\Messages\Gradido\StateGroupChangeParent $groupChangeParent
     *     @type \Model\Messages\Gradido\Transfer $transfer
     *     @type \Model\Messages\Gradido\TransactionCreation $creation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransactionBody::initOnce();
        parent::__construct($data);
    }

    /**
     * max 150 chars
     *
     * Generated from protobuf field <code>string memo = 1;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * max 150 chars
     *
     * Generated from protobuf field <code>string memo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.TimestampSeconds created = 2;</code>
     * @return \Model\Messages\Gradido\TimestampSeconds
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.TimestampSeconds created = 2;</code>
     * @param \Model\Messages\Gradido\TimestampSeconds $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\TimestampSeconds::class);
        $this->created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.StateCreateGroup createGroup = 6;</code>
     * @return \Model\Messages\Gradido\StateCreateGroup
     */
    public function getCreateGroup()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.StateCreateGroup createGroup = 6;</code>
     * @param \Model\Messages\Gradido\StateCreateGroup $var
     * @return $this
     */
    public function setCreateGroup($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\StateCreateGroup::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.StateGroupChangeParent groupChangeParent = 7;</code>
     * @return \Model\Messages\Gradido\StateGroupChangeParent
     */
    public function getGroupChangeParent()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.StateGroupChangeParent groupChangeParent = 7;</code>
     * @param \Model\Messages\Gradido\StateGroupChangeParent $var
     * @return $this
     */
    public function setGroupChangeParent($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\StateGroupChangeParent::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Transfer transfer = 8;</code>
     * @return \Model\Messages\Gradido\Transfer
     */
    public function getTransfer()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.Transfer transfer = 8;</code>
     * @param \Model\Messages\Gradido\Transfer $var
     * @return $this
     */
    public function setTransfer($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\Transfer::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.TransactionCreation creation = 9;</code>
     * @return \Model\Messages\Gradido\TransactionCreation
     */
    public function getCreation()
    {
        return $this->readOneof(9);
    }

    /**
     * Generated from protobuf field <code>.model.messages.gradido.TransactionCreation creation = 9;</code>
     * @param \Model\Messages\Gradido\TransactionCreation $var
     * @return $this
     */
    public function setCreation($var)
    {
        GPBUtil::checkMessage($var, \Model\Messages\Gradido\TransactionCreation::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

