#include "gradido_blockchain_core/types/ledger_anchor.h"

const char *grdt_ledger_anchor_to_string(grdt_ledger_anchor ledger_anchor) {
  static const char *messages[] = {
      [GRDT_LEDGER_ANCHOR_UNSPECIFIED] = "GRDT_LEDGER_ANCHOR_UNSPECIFIED",
      [GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID] = "GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID",
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID] =
          "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID",
      [GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID] =
          "GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID",
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID] =
          "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID",
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID] =
          "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID",
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID] =
          "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID",
      [GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID] =
          "GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID",
  };

  if (ledger_anchor < 0 || ledger_anchor >= (int)(sizeof(messages) / sizeof(messages[0]))) {
    return "GRDT_LEDGER_ANCHOR_UNKNOWN";
  }

  const char *msg = messages[ledger_anchor];
  return msg ? msg : "GRDT_LEDGER_ANCHOR_UNKNOWN";
}