#include "gradido_blockchain_core/types/transaction.h"

const char *grdt_transaction_to_string(grdt_transaction transaction) {
  static const char *messages[] = {
      [GRDT_TRANSACTION_NONE] = "GRDT_TRANSACTION_NONE",
      [GRDT_TRANSACTION_CREATION] = "GRDT_TRANSACTION_CREATION",
      [GRDT_TRANSACTION_TRANSFER] = "GRDT_TRANSACTION_TRANSFER",
      [GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE] = "GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE",
      [GRDT_TRANSACTION_REGISTER_ADDRESS] = "GRDT_TRANSACTION_REGISTER_ADDRESS",
      [GRDT_TRANSACTION_DEFERRED_TRANSFER] = "GRDT_TRANSACTION_DEFERRED_TRANSFER",
      [GRDT_TRANSACTION_COMMUNITY_ROOT] = "GRDT_TRANSACTION_COMMUNITY_ROOT",
      [GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER] = "GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER",
      [GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER] = "GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER",
  };

  if (transaction < 0 || transaction >= (int)(sizeof(messages) / sizeof(messages[0]))) {
    return "GRDT_TRANSACTION_UNKNOWN";
  }

  const char *msg = messages[transaction];
  return msg ? msg : "GRDT_TRANSACTION_UNKNOWN";
}