const GRDT_LEDGER_ANCHOR_TYPES = [
  'GRDT_LEDGER_ANCHOR_UNSPECIFIED',
  'GRDT_LEDGER_ANCHOR_IOTA_MESSAGE_ID', // not used any more, but stay for not disturbing indices
  'GRDT_LEDGER_ANCHOR_HIERO_TRANSACTION_ID',
  'GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_ID',
  'GRDT_LEDGER_ANCHOR_NODE_TRIGGER_TRANSACTION_ID',
  'GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_COMMUNITY_ID',
  'GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_USER_ID',
  'GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_CONTRIBUTION_ID',
  'GRDT_LEDGER_ANCHOR_LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID',
]

// The type is derived directly from the array
// for runtime check
function isGrdtLedgerAnchorType(input) {
  return GRDT_LEDGER_ANCHOR_TYPES.includes(input)
}

module.exports = {
  GRDT_LEDGER_ANCHOR_TYPES,
  isGrdtLedgerAnchorType,
}
