const GRDT_TRANSACTION_TYPES = [
  'GRDT_TRANSACTION_NONE',
  'GRDT_TRANSACTION_CREATION',
  'GRDT_TRANSACTION_TRANSFER',
  'GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE',
  'GRDT_TRANSACTION_REGISTER_ADDRESS',
  'GRDT_TRANSACTION_DEFERRED_TRANSFER',
  'GRDT_TRANSACTION_COMMUNITY_ROOT',
  'GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER',
  'GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER',
]

// The type is derived directly from the array
// for runtime check
function isGrdtTransactionType(input) {
  return GRDT_TRANSACTION_TYPES.includes(input)
}

module.exports = {
  GRDT_TRANSACTION_TYPES,
  isGrdtTransactionType,
}
