import { registerEnumType } from 'type-graphql'

/**
 * Transaction Types on Blockchain
 */
export enum TransactionType {
  GRDT_TRANSACTION_TRANSFER = 'GRDT_TRANSACTION_TRANSFER',
  GRDT_TRANSACTION_CREATION = 'GRDT_TRANSACTION_CREATION',
  GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE = 'GRDT_TRANSACTION_COMMUNITY_FRIENDS_UPDATE',
  GRDT_TRANSACTION_REGISTER_ADDRESS = 'GRDT_TRANSACTION_REGISTER_ADDRESS',
  GRDT_TRANSACTION_DEFERRED_TRANSFER = 'GRDT_TRANSACTION_DEFERRED_TRANSFER',
  GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER = 'GRDT_TRANSACTION_REDEEM_DEFERRED_TRANSFER',
  GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER = 'GRDT_TRANSACTION_TIMEOUT_DEFERRED_TRANSFER',
  GRDT_TRANSACTION_COMMUNITY_ROOT = 'GRDT_TRANSACTION_COMMUNITY_ROOT',
}

registerEnumType(TransactionType, {
  name: 'TransactionType', // this one is mandatory
  description: 'Type of the transaction', // this one is optional
})
