import { RIGHTS } from './RIGHTS'

export const ADMIN_RIGHTS = [
  RIGHTS.SET_USER_ROLE,
  RIGHTS.DELETE_USER,
  RIGHTS.UNDELETE_USER,
  RIGHTS.COMMUNITY_UPDATE,
  RIGHTS.COMMUNITY_BY_UUID,
  RIGHTS.COMMUNITY_BY_IDENTIFIER,
  RIGHTS.HOME_COMMUNITY,
]
