import { RIGHTS } from './RIGHTS'

export const ADMIN_RIGHTS = [
  RIGHTS.SET_USER_ROLE,
  RIGHTS.DELETE_USER,
  RIGHTS.UNDELETE_USER,
  RIGHTS.COMMUNITY_UPDATE,
  RIGHTS.COMMUNITY_WITH_API_KEYS,
  RIGHTS.PROJECT_BRANDING_MUTATE,
]
