import { RIGHTS } from './RIGHTS'

export const INALIENABLE_RIGHTS = [
  RIGHTS.LOGIN,
  RIGHTS.COMMUNITIES,
  RIGHTS.CREATE_USER,
  RIGHTS.SEND_RESET_PASSWORD_EMAIL,
  RIGHTS.SET_PASSWORD,
  RIGHTS.QUERY_TRANSACTION_LINK,
  RIGHTS.QUERY_OPT_IN,
  RIGHTS.CHECK_USERNAME,
]
