import { RIGHTS } from './RIGHTS'

export const MODERATOR_RIGHTS = [
  RIGHTS.SEARCH_USERS,
  RIGHTS.ADMIN_CREATE_CONTRIBUTION,
  RIGHTS.ADMIN_UPDATE_CONTRIBUTION,
  RIGHTS.ADMIN_DELETE_CONTRIBUTION,
  RIGHTS.ADMIN_LIST_CONTRIBUTIONS,
  RIGHTS.CONFIRM_CONTRIBUTION,
  RIGHTS.SEND_ACTIVATION_EMAIL,
  RIGHTS.LIST_TRANSACTION_LINKS_ADMIN,
  // Creating, changing and deleting starting-balance links is an administrator's job — see
  // ADMIN_RIGHTS. Moderators keep LIST_CONTRIBUTION_LINKS (it sits in USER_RIGHTS) so they
  // can still look the links up and pass them on as promotional material.
  RIGHTS.ADMIN_CREATE_CONTRIBUTION_MESSAGE,
  RIGHTS.MODERATOR_UPDATE_CONTRIBUTION_MEMO,
  RIGHTS.ADMIN_LIST_ALL_CONTRIBUTION_MESSAGES,
  RIGHTS.DENY_CONTRIBUTION,
  RIGHTS.ADMIN_OPEN_CREATIONS,
  RIGHTS.VIEW_USER_CONTACT,
]
