import { RIGHTS } from './RIGHTS'

export const MODERATOR_RIGHTS = [
  RIGHTS.SEARCH_USERS,
  RIGHTS.ADMIN_CREATE_CONTRIBUTION,
  RIGHTS.ADMIN_UPDATE_CONTRIBUTION,
  RIGHTS.ADMIN_DELETE_CONTRIBUTION,
  RIGHTS.ADMIN_LIST_CONTRIBUTIONS,
  RIGHTS.CONFIRM_CONTRIBUTION,
  RIGHTS.SEND_ACTIVATION_EMAIL,
  RIGHTS.LIST_TRANSACTION_LINKS_ADMIN,
  RIGHTS.CREATE_CONTRIBUTION_LINK,
  RIGHTS.DELETE_CONTRIBUTION_LINK,
  RIGHTS.UPDATE_CONTRIBUTION_LINK,
  RIGHTS.ADMIN_CREATE_CONTRIBUTION_MESSAGE,
  RIGHTS.MODERATOR_UPDATE_CONTRIBUTION_MEMO,
  RIGHTS.ADMIN_LIST_ALL_CONTRIBUTION_MESSAGES,
  RIGHTS.DENY_CONTRIBUTION,
  RIGHTS.ADMIN_OPEN_CREATIONS,
  RIGHTS.VIEW_USER_CONTACT,
]
