import { MATCHING_RIGHTS } from './MATCHING_RIGHTS'
import { RIGHTS } from './RIGHTS'

export const USER_RIGHTS = [
  RIGHTS.VERIFY_LOGIN,
  RIGHTS.BALANCE,
  RIGHTS.LIST_GDT_ENTRIES,
  RIGHTS.EXIST_PID,
  RIGHTS.UNSUBSCRIBE_NEWSLETTER,
  RIGHTS.SUBSCRIBE_NEWSLETTER,
  RIGHTS.TRANSACTION_LIST,
  RIGHTS.SEND_COINS,
  RIGHTS.LOGOUT,
  RIGHTS.UPDATE_USER_INFOS,
  RIGHTS.HAS_ELOPAGE,
  RIGHTS.CREATE_TRANSACTION_LINK,
  RIGHTS.DELETE_TRANSACTION_LINK,
  RIGHTS.REDEEM_TRANSACTION_LINK,
  RIGHTS.DISBURSE_TRANSACTION_LINK,
  RIGHTS.LIST_TRANSACTION_LINKS,
  RIGHTS.GDT_BALANCE,
  RIGHTS.CREATE_CONTRIBUTION,
  RIGHTS.DELETE_CONTRIBUTION,
  RIGHTS.LIST_CONTRIBUTIONS,
  RIGHTS.LIST_ALL_CONTRIBUTIONS,
  RIGHTS.UPDATE_CONTRIBUTION,
  RIGHTS.SEARCH_ADMIN_USERS,
  RIGHTS.LIST_CONTRIBUTION_LINKS,
  RIGHTS.COMMUNITY_STATISTICS,
  RIGHTS.CREATE_CONTRIBUTION_MESSAGE,
  RIGHTS.LIST_ALL_CONTRIBUTION_MESSAGES,
  RIGHTS.OPEN_CREATIONS,
  RIGHTS.USER,
  RIGHTS.GMS_USER_PLAYGROUND,
  RIGHTS.HUMHUB_AUTO_LOGIN,
  RIGHTS.PROJECT_BRANDING_VIEW,
  RIGHTS.LIST_HUMHUB_SPACES,
  RIGHTS.VIEW_USER_CONTACT,
  RIGHTS.LIST_CREATION_GROUPS,
  RIGHTS.MANAGE_OWN_CREATION_GROUPS,
  RIGHTS.LIST_ACTIVE_MODULES,
  // Matching: a member's own entry. Inert while the matching module is off, which is how
  // it ships. Granting them here is safe because isAuthorized does not merely refuse them
  // on the @Authorized path -- it takes them off the role itself, so Role.hasRight()
  // answers no as well and a field-level guard written that way is covered too. See
  // data/Module.logic.ts, and isAuthorized.test.ts, which holds that invariant.
  ...MATCHING_RIGHTS,
]
