export enum CommunityHandshakeStateType { 
  START_COMMUNITY_AUTHENTICATION = 'START_COMMUNITY_AUTHENTICATION',
  OPEN_CONNECTION = 'OPEN_CONNECTION',
  OPEN_CONNECTION_CALLBACK = 'OPEN_CONNECTION_CALLBACK',
  
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED'
}