export enum CommunityHandshakeStateType { 
  START_COMMUNITY_AUTHENTICATION = 'START_COMMUNITY_AUTHENTICATION',
  START_OPEN_CONNECTION_CALLBACK = 'START_OPEN_CONNECTION_CALLBACK',
  START_AUTHENTICATION = 'START_AUTHENTICATION',
  
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED'
}