name: Gradido Database Test CI

on:
  push:
    paths:
      - 'database/**'
      - 'shared/**'
      - 'shared-native/**'
      - 'docker-compose.*'
      - '.bun-version'
      - '.nvmrc'
      - '.github/workflows/test_database.yml'

jobs:
  build:
    name: Docker Build Test - Database up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Database | Build image
        run: docker build --target up -t "gradido/database:up" -f database/Dockerfile .

  database_migration_test:
    name: Database Migration Test & Build & Typecheck - Up + Reset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Database | docker-compose
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --detach mariadb redis

      - name: install bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: install dependencies
        run: |
          bun install --filter database --frozen-lockfile
          bun install --global --no-save turbo@^2

      - name: Database | build
        run: turbo database#build
      - name: Database | up + test
        run: turbo database#test database#typecheck
      
      - name: Database | reset
        run: turbo database#reset
