name: Gradido Admin Interface Test CI

on:
  push:
    branches:
      - 2664-refactordevops-refine-test-ci-workflow

jobs:
  build_base_admin:
    name: Docker Build 'base' Admin Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Admin | Build 'base' image
        run: |
          docker build --target base -t "gradido/admin:base" admin/ --build-arg NODE_ENV="test"
          docker save "gradido/admin:base" > /tmp/admin.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-admin-base
          path: /tmp/admin.tar

  lint_admin:
    name: Lint Admin Interface
    runs-on: ubuntu-latest
    needs: [build_base_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-base
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Admin Interface | Lint
        run: docker run --rm -v /home/runner/work/gradido/gradido/admin:/app gradido/admin:base sh -c "yarn && yarn run lint"

  stylelint_admin:
    name: Stylelint Admin Interface
    runs-on: ubuntu-latest
    needs: [build_base_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-base
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Admin Interface | Stylelint
        run: docker run --rm -v /home/runner/work/gradido/gradido/admin:/app gradido/admin:base sh -c "yarn && yarn run stylelint"

  locales_admin:
    name: Locales Admin Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: admin | Locales
        run: |
          cd admin
          yarn run locales

  unit_test_admin:
    name: Unit Tests Admin Interface
    runs-on: ubuntu-latest
    needs: [build_base_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-base
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Admin Interface | Unit tests
        run: |
          docker run --rm -v /home/runner/work/gradido/gradido/admin:/app gradido/admin:base sh -c "yarn && yarn run test"
          cp -r /home/runner/work/gradido/gradido/admin ./coverage

      - name: Admin Interface | Coverage check
        uses: webcraftmedia/coverage-check-action@master
        with:
          report_name: Coverage Admin Interface
          type: lcov
          result_path: ./coverage/lcov.info
          min_coverage: 96
          token: ${{ github.token }}
