name: Gradido Admin Interface Test CI

on:
  push:
    branches:
      - 2664-refactordevops-refine-test-ci-workflow

jobs:
  # DOCKER BUILD TEST ADMIN INTERFACE
  build_development_admin:
    name: Docker Build 'development' Admin Interface
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Admin | Build 'development' image
        run: |
          docker build --target development -t "gradido/admin:development" admin/ --build-arg NODE_ENV="test"
          docker save "gradido/admin:development" > /tmp/admin.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-admin-development
          path: /tmp/admin.tar

  # LINT ADMIN INTERFACE
  lint_admin:
    name: Lint - Admin Interface
    runs-on: ubuntu-latest
    needs: [build_development_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-development
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Admin Interface | Lint
        run: docker run --rm gradido/admin:development cd admin && yarn run lint

  # STYLELINT ADMIN INTERFACE
  stylelint_admin:
    name: Stylelint - Admin Interface
    runs-on: ubuntu-latest
    needs: [build_development_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-development"
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Admin Interface | Stylelint
        run: docker run --rm gradido/admin:development cd admin && yarn run stylelint

  # LOCALES ADMIN
  locales_admin:
    name: Locales - Admin Interface
    runs-on: ubuntu-latest
    needs: [build_development_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-development"
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-development"
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: admin | Locales
        run: docker run --rm gradido/admin:development yarn run locales

  # UNIT TEST ADMIN INTERFACE
  unit_test_admin:
    name: Unit tests - Admin Interface
    runs-on: ubuntu-latest
    needs: [build_development_admin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image (Admin Interface)
        uses: actions/download-artifact@v3
        with:
          name: docker-admin-development"
          path: /tmp

      - name: Load Docker Image
        run: docker load < /tmp/admin.tar

      - name: Admin Interface | Unit tests
        run: |
          docker run -v ~/coverage:/app/coverage --rm gradido/admin:development cd admin && yarn run test
          cp -r ~/coverage ./coverage

      - name: Admin Interface | Coverage check
        uses: webcraftmedia/coverage-check-action@master
        with:
          report_name: Coverage Admin Interface
          type: lcov
          result_path: ./coverage/lcov.info
          min_coverage: 96
          token: ${{ github.token }}
