name: Gradido Submodules Test CI

on: push

jobs:
  files-changed:
    name: Detect File Changes - Submodules
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.changes.outputs.core }}
      database: ${{ steps.changes.outputs.database }}
      shared: ${{ steps.changes.outputs.shared }}
      shared-native: ${{ steps.changes.outputs.shared-native }}
      config: ${{ steps.changes.outputs.config }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Check for core file changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  build-windows:
    name: Build Windows - Submodules
    if:  needs.files-changed.outputs.shared-native == 'true' || needs.files-changed.outputs.shared == 'true'
    needs: files-changed
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: install bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: install dependencies
        run: |
          bun install --filter shared --frozen-lockfile
          bun install --global turbo@^2

      - name: test shared and shared-native
        run: turbo shared#test shared-native#test
  
  build:
    name: Unit Tests & Typecheck & Build - Submodules
    if: needs.files-changed.outputs.core == 'true' || needs.files-changed.outputs.database == 'true' || needs.files-changed.outputs.shared == 'true' || needs.files-changed.outputs.shared-native == 'true' || needs.files-changed.outputs.config == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc' 
        
      - name: install bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Database & redis for tests using database and/or redis-semaphore
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --detach mariadb redis

      - name: install dependencies
        run: |
          bun install --filter core --frozen-lockfile
          bun install --global turbo@^2

      - name: test shared-native
        run: turbo shared-native#test
      - name: typecheck, locales && unit test
        run: turbo core#typecheck core#locales database#test database#typecheck shared#test shared#typecheck shared-native#test shared-native#typecheck config-schema#test config-schema#typecheck
      - name: core test extra
        run: turbo core#test
      - name: test with node js test runner and therefore windows napi nodejs addon
        run: cd shared-native && bun run test:node

