name: Gradido DLT Connector Test CI

on:
  push:
    paths:
      - 'dlt-connector/**'
      - 'docker-compose.*'
      - '.github/workflows/test_dlt_connector.yml'

jobs:
  build:
    name: Docker Build Test - DLT Connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create .env
        run: |
          cd dlt-connector
          cat <<EOF > .env  
          GRADIDO_BLOCKCHAIN_CRYPTO_APP_SECRET=$(openssl rand -hex 16)
          GRADIDO_BLOCKCHAIN_SERVER_CRYPTO_KEY=$(openssl rand -hex 16)
          HOME_COMMUNITY_SEED=$(openssl rand -hex 32)
          HIERO_OPERATOR_KEY=$(openssl rand -hex 32)
          HIERO_OPERATOR_ID="0.0.2"
          EOF
      
      - name: Build 'test' image
        run: docker build --target production -t "gradido/dlt-connector:productionTest" -f dlt-connector/Dockerfile .

  unit_test:
    name: Unit Tests & Typecheck & Build - DLT Connector
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: install bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: install dependencies
        run: bun install --filter shared --frozen-lockfile && cd dlt-connector && bun install --frozen-lockfile

      - name: typecheck && unit test
        run: |
          export GRADIDO_BLOCKCHAIN_CRYPTO_APP_SECRET=$(openssl rand -hex 16)
          export GRADIDO_BLOCKCHAIN_SERVER_CRYPTO_KEY=$(openssl rand -hex 16)
          export HOME_COMMUNITY_SEED=$(openssl rand -hex 32)
          export HIERO_OPERATOR_KEY=$(openssl rand -hex 32)
          export HIERO_OPERATOR_ID="0.0.2"
          cd dlt-connector && bun typecheck && bun test

