name: Gradido Frontend Test CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'config-schema/**'
      - '.bun-version'
      - '.nvmrc'
      - '.github/workflows/test_frontend.yml'

jobs:
  build_test:
    name: Docker Build Test - Frontend
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Frontend | Build 'test' image
        run: docker build -f ./frontend/Dockerfile --target production -t "gradido/frontend:production" --build-arg NODE_ENV="production" --build-arg BUILD_COMMIT=$(git rev-parse HEAD) --build-arg BUILD_COMMIT_SHORT=$(git rev-parse --short HEAD) .

  unit_test:
    name: Unit Tests & Lint & Stylelint & Locales - Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      
      - name: install bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: install dependencies
        run: |
          bun install --filter frontend --frozen-lockfile
          bun install --global --no-save turbo@^2

      - name: Frontend | Unit tests
        run: turbo frontend#test frontend#lint frontend#locales

