name: Gradido Deploy Test CI

on: push

jobs:
  files-changed:
    name: Detect File Changes - Deploy Bare Metal
    runs-on: ubuntu-latest
    outputs:
      deploy-bare-metal: ${{ steps.changes.outputs.deploy-bare-metal }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for deploy-bare-metal file changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  build_test:
    if: needs.files-changed.outputs.deploy-bare-metal == 'true'
    name: Docker Build Test - Deploy Bare Metal
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Bare Metal | Build image
        run: docker build -f ./deployment/bare_metal/Dockerfile --build-arg BRANCH_NAME=${{ github.ref_name }} -t "gradido/deploy-bare-metal:local" .
