name: Gradido Admin Interface Test CI

on:
  push:
    paths:
      - 'admin/**'
      - 'config-schema/**'
      - '.github/workflows/test_admin_interface.yml'

jobs:
  build_test:
    name: Docker Build Test - Admin Interface
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Admin Interface | Build 'test' image
        run: docker build -f ./admin/Dockerfile --target production -t "gradido/admin:production" --build-arg NODE_ENV="production" --build-arg BUILD_COMMIT=$(git rev-parse HEAD) --build-arg BUILD_COMMIT_SHORT=$(git rev-parse --short HEAD) .

  unit_test_lint:
    name: Unit Tests & Lint & Stylelint & Locales - Admin Interface
    runs-on: ubuntu-latest
    outputs:
      test-success: ${{ steps.test.outputs.success }}
    steps:
      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.7'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: install bun 
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: install dependencies
        run: |
          bun install --filter admin --frozen-lockfile
          bun install --global --no-save turbo@^2

      - name: Admin Interface | Unit tests
        id: test
        run: |
          turbo admin#test admin#lint admin#locales
